// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package quotedb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countQuotes = `-- name: CountQuotes :one
SELECT count(*) FROM quotes
`

func (q *Queries) CountQuotes(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countQuotes)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const findQuoteRevision = `-- name: FindQuoteRevision :one

SELECT id, superseded
FROM quotes
WHERE lang = $1 AND upstream_id = $2 AND text_hash = $3
`

type FindQuoteRevisionParams struct {
	Lang       string
	UpstreamID int32
	TextHash   string
}

type FindQuoteRevisionRow struct {
	ID         uuid.UUID
	Superseded bool
}

// --- import (make import-quotes) ---
// The revision of (lang, upstream_id) that already carries these exact bytes.
// Keyed on the hash rather than on the text so the comparison is an index
// lookup on quotes_revision_idx instead of a full text equality.
func (q *Queries) FindQuoteRevision(ctx context.Context, arg FindQuoteRevisionParams) (FindQuoteRevisionRow, error) {
	row := q.db.QueryRow(ctx, findQuoteRevision, arg.Lang, arg.UpstreamID, arg.TextHash)
	var i FindQuoteRevisionRow
	err := row.Scan(&i.ID, &i.Superseded)
	return i, err
}

const getQuote = `-- name: GetQuote :one
SELECT id, lang, upstream_id, text, source, length, len_group, text_hash,
       superseded, (withdrawn_at IS NOT NULL)::boolean AS withdrawn, created_at
FROM quotes
WHERE id = $1
`

type GetQuoteRow struct {
	ID         uuid.UUID
	Lang       string
	UpstreamID int32
	Text       string
	Source     string
	Length     int32
	LenGroup   int16
	TextHash   string
	Superseded bool
	Withdrawn  bool
	CreatedAt  time.Time
}

// One quote by id, text included, SUPERSEDED AND WITHDRAWN REVISIONS INCLUDED.
// This is the only read that crosses that line, and it has to: a run recorded
// against a retired or withdrawn quote must resolve its exact bytes forever or
// it stops being replayable — the same guarantee a frozen dict_hash gives
// seeded runs. Withdrawal is a discovery rule, never a resolution rule (00025).
//
// Both states ride along on the row so a client can say "this quote is no
// longer offered" instead of silently linking to something the browse endpoint
// will never return again.
func (q *Queries) GetQuote(ctx context.Context, id uuid.UUID) (GetQuoteRow, error) {
	row := q.db.QueryRow(ctx, getQuote, id)
	var i GetQuoteRow
	err := row.Scan(
		&i.ID,
		&i.Lang,
		&i.UpstreamID,
		&i.Text,
		&i.Source,
		&i.Length,
		&i.LenGroup,
		&i.TextHash,
		&i.Superseded,
		&i.Withdrawn,
		&i.CreatedAt,
	)
	return i, err
}

const getQuoteWithdrawal = `-- name: GetQuoteWithdrawal :one
SELECT id, lang, upstream_id, text, source, length, len_group, superseded,
       withdrawn_at, withdrawn_by, withdrawn_reason, created_at
FROM quotes
WHERE id = $1
`

type GetQuoteWithdrawalRow struct {
	ID              uuid.UUID
	Lang            string
	UpstreamID      int32
	Text            string
	Source          string
	Length          int32
	LenGroup        int16
	Superseded      bool
	WithdrawnAt     *time.Time
	WithdrawnBy     *uuid.UUID
	WithdrawnReason *string
	CreatedAt       time.Time
}

// The moderation view of one quote: identity plus the withdrawal record. Text
// included — a moderator deciding whether to withdraw a quote has to read it,
// and this route is behind a permission gate rather than on the public surface.
func (q *Queries) GetQuoteWithdrawal(ctx context.Context, id uuid.UUID) (GetQuoteWithdrawalRow, error) {
	row := q.db.QueryRow(ctx, getQuoteWithdrawal, id)
	var i GetQuoteWithdrawalRow
	err := row.Scan(
		&i.ID,
		&i.Lang,
		&i.UpstreamID,
		&i.Text,
		&i.Source,
		&i.Length,
		&i.LenGroup,
		&i.Superseded,
		&i.WithdrawnAt,
		&i.WithdrawnBy,
		&i.WithdrawnReason,
		&i.CreatedAt,
	)
	return i, err
}

const insertQuoteRevision = `-- name: InsertQuoteRevision :one
INSERT INTO quotes (id, lang, upstream_id, text, source, length, len_group, text_hash)
VALUES (gen_random_uuid(), $1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type InsertQuoteRevisionParams struct {
	Lang       string
	UpstreamID int32
	Text       string
	Source     string
	Length     int32
	LenGroup   int16
	TextHash   string
}

// Publish new bytes under an existing or new (lang, upstream_id). The id is
// generated here rather than in Go so the whole import is one round trip per
// statement and the database owns row identity, as everywhere else.
func (q *Queries) InsertQuoteRevision(ctx context.Context, arg InsertQuoteRevisionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertQuoteRevision,
		arg.Lang,
		arg.UpstreamID,
		arg.Text,
		arg.Source,
		arg.Length,
		arg.LenGroup,
		arg.TextHash,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listQuotes = `-- name: ListQuotes :many

SELECT id, lang, upstream_id, source, length, len_group, text_hash, created_at
FROM quotes
WHERE NOT superseded
  AND withdrawn_at IS NULL
  AND ($1::text IS NULL OR lang = $1::text)
  AND ($2::smallint IS NULL OR len_group = $2::smallint)
  AND (NOT $3::boolean
       OR (lang, len_group, id) > ($4::text, $5::smallint, $6::uuid))
ORDER BY lang, len_group, id
LIMIT $7
`

type ListQuotesParams struct {
	Lang        *string
	LenGroup    *int16
	AfterCursor bool
	AfterLang   string
	AfterGroup  int16
	AfterID     uuid.UUID
	RowLimit    int32
}

type ListQuotesRow struct {
	ID         uuid.UUID
	Lang       string
	UpstreamID int32
	Source     string
	Length     int32
	LenGroup   int16
	TextHash   string
	CreatedAt  time.Time
}

// The quote registry (docs/QUOTES.md).
//
// Reads are public and text-frugal: the browse queries never SELECT `text`, so
// the corpus cannot be walked out of the database through the paging endpoint
// even by a handler bug — the column is not in the result set to leak.
//
// Writes happen only in `make import-quotes`. Nothing here UPDATEs `text`:
// publishing a corrected quote inserts a new revision and retires the old one,
// because every stored run resolves its bytes through the row it was played on.
// One page of published quote metadata, in the browse ordering.
//
// (lang, len_group, id) is the quotes_browse_idx column list, so the index
// supplies the order and the page is an ordered index scan rather than a sort.
// The trailing id is a primary key, which makes the ordering TOTAL — the
// property keyset pagination needs, and the reason a row inserted before the
// cursor cannot shuffle anything the walk has already returned.
//
// The optional filters are written as `$n IS NULL OR col = $n` rather than as
// separate query variants. With a bound parameter Postgres folds the IS NULL
// away in a custom plan and uses the column as a scan key; under a generic plan
// it degrades to a filter over the partial index, which on a 2 286-row corpus
// is an index-only scan measured in microseconds. Six near-identical queries
// would buy nothing but six converters to keep in step.
//
// `withdrawn_at IS NULL` joins `NOT superseded` as the OTHER half of "published"
// (00025). Both are in quotes_browse_idx's partial predicate, so neither costs a
// filter; they are separate columns because they have separate owners — the
// importer moves one, a moderator moves the other.
func (q *Queries) ListQuotes(ctx context.Context, arg ListQuotesParams) ([]ListQuotesRow, error) {
	rows, err := q.db.Query(ctx, listQuotes,
		arg.Lang,
		arg.LenGroup,
		arg.AfterCursor,
		arg.AfterLang,
		arg.AfterGroup,
		arg.AfterID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListQuotesRow{}
	for rows.Next() {
		var i ListQuotesRow
		if err := rows.Scan(
			&i.ID,
			&i.Lang,
			&i.UpstreamID,
			&i.Source,
			&i.Length,
			&i.LenGroup,
			&i.TextHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWithdrawnQuoteIDs = `-- name: ListWithdrawnQuoteIDs :many
SELECT id FROM quotes WHERE withdrawn_at IS NOT NULL
`

// Every withdrawn quote, id only. The leaderboard's board index reads this to
// drop those boards from its listing; it is a separate query rather than a join
// because rebuilding a bucket key in SQL would make a second producer of a
// format that has exactly one (internal/leaderboard/bucket.go).
//
// Served index-only from quotes_withdrawn_idx over a set that is normally
// empty, which is what makes it affordable on a public read path.
func (q *Queries) ListWithdrawnQuoteIDs(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listWithdrawnQuoteIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pickRandomQuote = `-- name: PickRandomQuote :one
WITH candidates AS NOT MATERIALIZED (
    SELECT id
    FROM quotes
    WHERE NOT superseded
      AND withdrawn_at IS NULL
      AND ($1::text IS NULL OR lang = $1::text)
      AND ($2::smallint IS NULL OR len_group = $2::smallint)
),
pick AS (
    SELECT id FROM candidates
    OFFSET (SELECT floor(random() * count(*))::bigint FROM candidates)
    LIMIT 1
)
SELECT q.id, q.lang, q.upstream_id, q.text, q.source, q.length, q.len_group,
       q.text_hash, q.superseded, q.created_at
FROM quotes q
         JOIN pick ON pick.id = q.id
`

type PickRandomQuoteParams struct {
	Lang     *string
	LenGroup *int16
}

type PickRandomQuoteRow struct {
	ID         uuid.UUID
	Lang       string
	UpstreamID int32
	Text       string
	Source     string
	Length     int32
	LenGroup   int16
	TextHash   string
	Superseded bool
	CreatedAt  time.Time
}

// One published quote, drawn uniformly from the rows the filter admits.
//
// Done in SQL, and deliberately NOT `ORDER BY random() LIMIT 1`: that sorts the
// whole filtered corpus to throw all of it away but one row. This counts the
// candidates and then jumps to one offset among them, both reads served by
// quotes_browse_idx as INDEX-ONLY scans — `id` is in the index and the partial
// predicate already excludes superseded rows, so neither read touches the heap
// and there is no Sort node anywhere in the plan.
//
// NOT MATERIALIZED is load-bearing. `candidates` is referenced twice, which by
// default makes Postgres build a tuplestore and scan it twice; inlining it
// turns both references back into index-only scans and measured 3.9 ms -> 2.2 ms
// on english, the largest corpus (docs/QUOTES.md, "Random selection"). Written
// once rather than as two copies of the predicate so the filter cannot drift.
//
// It is O(candidates) rather than O(log n): the count is what forces a full
// pass. That is the price of an EXACTLY uniform draw, and it is the right trade
// here — see docs/QUOTES.md for the index-probe alternative and why a
// gap-weighted draw was not worth an extra index.
func (q *Queries) PickRandomQuote(ctx context.Context, arg PickRandomQuoteParams) (PickRandomQuoteRow, error) {
	row := q.db.QueryRow(ctx, pickRandomQuote, arg.Lang, arg.LenGroup)
	var i PickRandomQuoteRow
	err := row.Scan(
		&i.ID,
		&i.Lang,
		&i.UpstreamID,
		&i.Text,
		&i.Source,
		&i.Length,
		&i.LenGroup,
		&i.TextHash,
		&i.Superseded,
		&i.CreatedAt,
	)
	return i, err
}

const republishQuoteRevision = `-- name: RepublishQuoteRevision :execrows
UPDATE quotes
SET superseded = false
WHERE id = $1 AND superseded
`

// Un-retire a revision whose bytes upstream has reverted to. Also not a text
// edit: it only moves which revision of the key is the current one, and the
// rowcount is 0 whenever the revision was already current — which is what keeps
// an unchanged re-import reporting unchanged.
func (q *Queries) RepublishQuoteRevision(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, republishQuoteRevision, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const restoreQuote = `-- name: RestoreQuote :execrows
UPDATE quotes
SET withdrawn_at = NULL, withdrawn_by = NULL, withdrawn_reason = NULL
WHERE id = $1 AND withdrawn_at IS NOT NULL
`

// Put a withdrawn quote back into circulation. The rowcount is 0 when there was
// nothing to restore, which is how the handler answers idempotently rather than
// inventing a 404 for a quote that exists and was simply never withdrawn.
func (q *Queries) RestoreQuote(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, restoreQuote, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const supersedeOtherRevisions = `-- name: SupersedeOtherRevisions :execrows
UPDATE quotes
SET superseded = true
WHERE lang = $1 AND upstream_id = $2 AND id <> $3 AND NOT superseded
`

type SupersedeOtherRevisionsParams struct {
	Lang       string
	UpstreamID int32
	KeepID     uuid.UUID
}

// Retire every OTHER published revision of this key. Note what it does not do:
// it never touches `text`, so the retired row still serves the exact bytes its
// runs were played on. The rowcount is what tells the importer it superseded
// something rather than published a first revision.
func (q *Queries) SupersedeOtherRevisions(ctx context.Context, arg SupersedeOtherRevisionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, supersedeOtherRevisions, arg.Lang, arg.UpstreamID, arg.KeepID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const withdrawQuote = `-- name: WithdrawQuote :one

UPDATE quotes
SET withdrawn_at     = coalesce(withdrawn_at, now()),
    withdrawn_by     = CASE WHEN withdrawn_at IS NULL THEN $1::uuid ELSE withdrawn_by END,
    withdrawn_reason = CASE WHEN withdrawn_at IS NULL THEN $2::text ELSE withdrawn_reason END
WHERE id = $3
RETURNING id, withdrawn_at, withdrawn_by, withdrawn_reason,
          -- Whether THIS call is the one that withdrew it. The comparison is
          -- against the transaction clock, so it is true only for the row this
          -- statement just changed.
          (withdrawn_at = now()) AS newly_withdrawn
`

type WithdrawQuoteParams struct {
	Actor  uuid.UUID
	Reason string
	ID     uuid.UUID
}

type WithdrawQuoteRow struct {
	ID              uuid.UUID
	WithdrawnAt     *time.Time
	WithdrawnBy     *uuid.UUID
	WithdrawnReason *string
	NewlyWithdrawn  bool
}

// --- moderation (the admin surface, docs/REPORTS.md) ---
// Take a quote out of circulation. Idempotent in the useful direction: a quote
// already withdrawn keeps its ORIGINAL withdrawal — the first moderator's
// timestamp, actor and reason are the record, and a second call must not
// rewrite who decided what and when. The returned row is what the handler
// diffs to answer "did this call change anything".
func (q *Queries) WithdrawQuote(ctx context.Context, arg WithdrawQuoteParams) (WithdrawQuoteRow, error) {
	row := q.db.QueryRow(ctx, withdrawQuote, arg.Actor, arg.Reason, arg.ID)
	var i WithdrawQuoteRow
	err := row.Scan(
		&i.ID,
		&i.WithdrawnAt,
		&i.WithdrawnBy,
		&i.WithdrawnReason,
		&i.NewlyWithdrawn,
	)
	return i, err
}
