// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package profiledb

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type ActiveBan struct {
	UserID uuid.UUID
}

type AuthIdentity struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	Provider        string
	ProviderSubject string
	Email           *string
	EmailVerified   bool
	CreatedAt       time.Time
}

type Ban struct {
	UserID uuid.UUID
	// Internal moderation note. NEVER exposed to the player: the banner they see is deliberately opaque (docs/MODERATION.md).
	Reason        string
	IssuedBy      *string
	IssuedAt      time.Time
	ExpiresAt     *time.Time
	ID            uuid.UUID
	RevokedAt     *time.Time
	IssuedByUser  *uuid.UUID
	RevokedByUser *uuid.UUID
}

type EmailToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Purpose   string
	TokenHash []byte
	ExpiresAt time.Time
	UsedAt    *time.Time
	CreatedAt time.Time
}

type KeyboardProjectedRun struct {
	RunID uuid.UUID
}

type LeaderboardEligibleRun struct {
	RunID          uuid.UUID
	UserID         uuid.UUID
	Mode           string
	DurationMs     *int32
	WordCount      *int32
	Lang           string
	TextSourceKind string
	QuoteID        *uuid.UUID
	Score          int64
	Wpm            float64
	Raw            float64
	Acc            float64
	Mods           json.RawMessage
	AchievedAt     time.Time
}

type LeaderboardEntry struct {
	BucketKey   string
	UserID      uuid.UUID
	RunID       uuid.UUID
	Score       int64
	Wpm         float64
	Raw         float64
	Acc         float64
	Grade       string
	Mods        json.RawMessage
	AchievedAt  time.Time
	QuoteSource *string
	SortKey     *int64
}

type LeaderboardRanked struct {
	BucketKey   string
	UserID      uuid.UUID
	RunID       uuid.UUID
	Score       int64
	Wpm         float64
	Raw         float64
	Acc         float64
	Grade       string
	Mods        json.RawMessage
	AchievedAt  time.Time
	QuoteSource *string
	SortKey     *int64
}

type LeaderboardRow struct {
	BucketKey   string
	UserID      uuid.UUID
	DisplayName string
	RunID       uuid.UUID
	Score       int64
	Wpm         float64
	Raw         float64
	Acc         float64
	Grade       string
	Mods        json.RawMessage
	AchievedAt  time.Time
	QuoteSource *string
	SortKey     *int64
}

type Match struct {
	ID        string
	RoomCode  string
	Name      string
	Settings  json.RawMessage
	Freemods  json.RawMessage
	Seed      int64
	DictHash  string
	Lang      string
	GoAt      time.Time
	EndedAt   time.Time
	CreatedAt time.Time
}

type MatchRun struct {
	ID          uuid.UUID
	MatchID     string
	PlayerID    string
	Nick        string
	UserID      *uuid.UUID
	Freemods    json.RawMessage
	Log         []byte
	BatchCount  int32
	FinalStatus string
	CreatedAt   time.Time
}

type Quote struct {
	ID              uuid.UUID
	Lang            string
	UpstreamID      int32
	Text            string
	Source          string
	Length          int32
	LenGroup        int16
	TextHash        string
	Superseded      bool
	CreatedAt       time.Time
	WithdrawnAt     *time.Time
	WithdrawnBy     *uuid.UUID
	WithdrawnReason *string
}

type Report struct {
	ID             uuid.UUID
	SubjectType    string
	SubjectUserID  *uuid.UUID
	SubjectQuoteID *uuid.UUID
	SubjectRunID   *uuid.UUID
	ReporterID     uuid.UUID
	Reason         string
	Comment        *string
	Status         string
	CreatedAt      time.Time
	ResolvedAt     *time.Time
	ResolvedBy     *uuid.UUID
	ResolutionNote *string
}

type Run struct {
	ID                      uuid.UUID
	UserID                  uuid.UUID
	Mode                    string
	DurationMs              *int32
	WordCount               *int32
	Lang                    string
	Seed                    int64
	DictHash                string
	Setup                   json.RawMessage
	ClientMetrics           json.RawMessage
	ClientScore             json.RawMessage
	ScoreVersion            int16
	Status                  string
	Log                     []byte
	LogBytes                int32
	CreatedAt               time.Time
	Attempts                int16
	LastError               *string
	RestartsSinceLastSubmit int32
}

type RunStatusOverride struct {
	ID         uuid.UUID
	RunID      uuid.UUID
	FromStatus string
	ToStatus   string
	Reason     string
	DecidedBy  uuid.UUID
	DecidedAt  time.Time
}

type RunVerdict struct {
	RunID         uuid.UUID
	UserID        uuid.UUID
	ServerMetrics []byte
	ServerScore   []byte
	Validation    json.RawMessage
	BundleSha     *string
	PolicyVersion *int16
	ValidatedAt   time.Time
}

type Session struct {
	ID         uuid.UUID
	TokenHash  []byte
	UserID     uuid.UUID
	CreatedAt  time.Time
	ExpiresAt  time.Time
	LastSeenAt time.Time
}

type User struct {
	ID                   uuid.UUID
	DisplayName          string
	CreatedAt            time.Time
	ProfilePublic        bool
	KeyboardPublic       bool
	UpdatedAt            time.Time
	Role                 string
	Bio                  *string
	Keyboard             *string
	DisplayNameChangedAt *time.Time
}

type UserBadge struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	BadgeCode    string
	GrantedAt    time.Time
	GrantedBy    *uuid.UUID
	RevokedAt    *time.Time
	RevokedBy    *uuid.UUID
	DisplayOrder *int32
}

type UserCredential struct {
	UserID       uuid.UUID
	Argon2idHash string
	UpdatedAt    time.Time
}

type UserKeyboardProfile struct {
	UserID        uuid.UUID
	KeyID         string
	Presses       int64
	Errors        int64
	IntervalSumMs float64
	IntervalCount int64
}

type UserLink struct {
	UserID uuid.UUID
	Kind   string
	Handle string
}
