// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package profiledb

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const getProfileActivity = `-- name: GetProfileActivity :many
SELECT (created_at AT TIME ZONE 'UTC')::date                        AS day,
       count(*)::int                                                AS tests,
       coalesce(sum((server_metrics ->> 'durationSec')::float8 * 1000)
                FILTER (WHERE status = 'accepted'), 0)::bigint      AS time_ms
FROM runs
WHERE user_id = $1 AND created_at >= $2
GROUP BY 1
ORDER BY 1
`

type GetProfileActivityParams struct {
	UserID    uuid.UUID
	CreatedAt time.Time
}

type GetProfileActivityRow struct {
	Day    time.Time
	Tests  int32
	TimeMs int64
}

// Daily buckets for the activity calendar: every submitted run counts as a
// test that day; the time column reads the server-verified durations that
// exist (accepted runs). Days with no runs are absent — the calendar renders
// the gaps itself.
func (q *Queries) GetProfileActivity(ctx context.Context, arg GetProfileActivityParams) ([]GetProfileActivityRow, error) {
	rows, err := q.db.Query(ctx, getProfileActivity, arg.UserID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProfileActivityRow{}
	for rows.Next() {
		var i GetProfileActivityRow
		if err := rows.Scan(&i.Day, &i.Tests, &i.TimeMs); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProfileCounts = `-- name: GetProfileCounts :one
SELECT count(*)::bigint                                            AS tests_completed,
       coalesce(sum(restarts_since_last_submit), 0)::bigint        AS restarts,
       coalesce(sum((server_metrics ->> 'durationSec')::float8 * 1000)
                FILTER (WHERE status = 'accepted'), 0)::bigint     AS time_typing_ms,
       coalesce(sum(((server_metrics -> 'chars' ->> 'correct')::float8
                   + (server_metrics -> 'chars' ->> 'incorrect')::float8
                   + (server_metrics -> 'chars' ->> 'extra')::float8
                   + (server_metrics ->> 'spaces')::float8) / 5)
                FILTER (WHERE status = 'accepted'), 0)::float8     AS estimated_words
FROM runs
WHERE user_id = $1
`

type GetProfileCountsRow struct {
	TestsCompleted int64
	Restarts       int64
	TimeTypingMs   int64
	EstimatedWords float64
}

// Counters + the two derived totals. time_typing_ms and estimated_words read
// server_metrics (accepted only): durationSec is the deadline-pinned duration
// the core measured, and the words estimate is the raw character volume
// (correct+incorrect+extra+spaces) over the conventional 5 chars/word.
func (q *Queries) GetProfileCounts(ctx context.Context, userID uuid.UUID) (GetProfileCountsRow, error) {
	row := q.db.QueryRow(ctx, getProfileCounts, userID)
	var i GetProfileCountsRow
	err := row.Scan(
		&i.TestsCompleted,
		&i.Restarts,
		&i.TimeTypingMs,
		&i.EstimatedWords,
	)
	return i, err
}

const getProfileHistogram = `-- name: GetProfileHistogram :many
SELECT (floor((server_metrics ->> 'wpm')::float8 / 10) * 10)::int AS bucket,
       count(*)::int                                              AS tests
FROM runs
WHERE user_id = $1 AND status = 'accepted'
GROUP BY 1
ORDER BY 1
`

type GetProfileHistogramRow struct {
	Bucket int32
	Tests  int32
}

// Tests per 10-wpm bucket over accepted runs; `bucket` is the lower bound
// (60 covers [60, 70)).
func (q *Queries) GetProfileHistogram(ctx context.Context, userID uuid.UUID) ([]GetProfileHistogramRow, error) {
	rows, err := q.db.Query(ctx, getProfileHistogram, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProfileHistogramRow{}
	for rows.Next() {
		var i GetProfileHistogramRow
		if err := rows.Scan(&i.Bucket, &i.Tests); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProfileLanguages = `-- name: GetProfileLanguages :one
SELECT (coalesce(jsonb_agg(jsonb_build_object('lang', lang, 'tests', tests)
                           ORDER BY tests DESC, lang), '[]'::jsonb))::jsonb AS languages
FROM (SELECT lang, count(*)::int AS tests
      FROM runs WHERE user_id = $1
      GROUP BY lang) t
`

// Per-language play counts over every submitted run, as one jsonb document —
// ordered most-played first.
func (q *Queries) GetProfileLanguages(ctx context.Context, userID uuid.UUID) (json.RawMessage, error) {
	row := q.db.QueryRow(ctx, getProfileLanguages, userID)
	var languages json.RawMessage
	err := row.Scan(&languages)
	return languages, err
}

const getProfileLast10 = `-- name: GetProfileLast10 :one
SELECT coalesce(avg(t.wpm), 0)::float8         AS wpm_average,
       coalesce(avg(t.raw), 0)::float8         AS raw_average,
       coalesce(avg(t.acc), 0)::float8         AS acc_average,
       coalesce(avg(t.consistency), 0)::float8 AS consistency_average
FROM (SELECT (server_metrics ->> 'wpm')::float8         AS wpm,
             (server_metrics ->> 'raw')::float8         AS raw,
             (server_metrics ->> 'accuracy')::float8    AS acc,
             (server_metrics ->> 'consistency')::float8 AS consistency
      FROM runs
      WHERE user_id = $1 AND status = 'accepted'
      ORDER BY created_at DESC, id DESC
      LIMIT 10) t
`

type GetProfileLast10Row struct {
	WpmAverage         float64
	RawAverage         float64
	AccAverage         float64
	ConsistencyAverage float64
}

// The same four metrics averaged over the LAST 10 accepted runs by date. The
// inner query walks (user_id, created_at DESC) newest-first and stops after
// ten accepted rows — no sort node, the index provides the order.
func (q *Queries) GetProfileLast10(ctx context.Context, userID uuid.UUID) (GetProfileLast10Row, error) {
	row := q.db.QueryRow(ctx, getProfileLast10, userID)
	var i GetProfileLast10Row
	err := row.Scan(
		&i.WpmAverage,
		&i.RawAverage,
		&i.AccAverage,
		&i.ConsistencyAverage,
	)
	return i, err
}

const getProfileMetricStats = `-- name: GetProfileMetricStats :one
SELECT coalesce(max((server_metrics ->> 'wpm')::float8), 0)::float8         AS wpm_highest,
       coalesce(avg((server_metrics ->> 'wpm')::float8), 0)::float8         AS wpm_average,
       coalesce(max((server_metrics ->> 'raw')::float8), 0)::float8         AS raw_highest,
       coalesce(avg((server_metrics ->> 'raw')::float8), 0)::float8         AS raw_average,
       coalesce(max((server_metrics ->> 'accuracy')::float8), 0)::float8    AS acc_highest,
       coalesce(avg((server_metrics ->> 'accuracy')::float8), 0)::float8    AS acc_average,
       coalesce(max((server_metrics ->> 'consistency')::float8), 0)::float8 AS consistency_highest,
       coalesce(avg((server_metrics ->> 'consistency')::float8), 0)::float8 AS consistency_average
FROM runs
WHERE user_id = $1 AND status = 'accepted'
`

type GetProfileMetricStatsRow struct {
	WpmHighest         float64
	WpmAverage         float64
	RawHighest         float64
	RawAverage         float64
	AccHighest         float64
	AccAverage         float64
	ConsistencyHighest float64
	ConsistencyAverage float64
}

// highest / average for the four profile metrics, over accepted runs.
func (q *Queries) GetProfileMetricStats(ctx context.Context, userID uuid.UUID) (GetProfileMetricStatsRow, error) {
	row := q.db.QueryRow(ctx, getProfileMetricStats, userID)
	var i GetProfileMetricStatsRow
	err := row.Scan(
		&i.WpmHighest,
		&i.WpmAverage,
		&i.RawHighest,
		&i.RawAverage,
		&i.AccHighest,
		&i.AccAverage,
		&i.ConsistencyHighest,
		&i.ConsistencyAverage,
	)
	return i, err
}

const getProfilePBs = `-- name: GetProfilePBs :many
SELECT bucket_key, run_id, score, wpm::float8 AS wpm, raw::float8 AS raw,
       acc::float8 AS acc, grade, mods, quote_source, achieved_at
FROM leaderboard_entries
WHERE user_id = $1
ORDER BY achieved_at DESC
`

type GetProfilePBsRow struct {
	BucketKey   string
	RunID       uuid.UUID
	Score       int64
	Wpm         float64
	Raw         float64
	Acc         float64
	Grade       string
	Mods        json.RawMessage
	QuoteSource *string
	AchievedAt  time.Time
}

// The PB cards: leaderboard_entries IS the per-bucket personal-best store (one
// row per player per bucket, projected from accepted runs), so this is a read,
// not a computation. Own-profile view — deliberately the raw entries table,
// not the ban-filtered leaderboard_rows: a player's own bests are their own
// data, and this surface is session-scoped to its owner.
func (q *Queries) GetProfilePBs(ctx context.Context, userID uuid.UUID) ([]GetProfilePBsRow, error) {
	rows, err := q.db.Query(ctx, getProfilePBs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProfilePBsRow{}
	for rows.Next() {
		var i GetProfilePBsRow
		if err := rows.Scan(
			&i.BucketKey,
			&i.RunID,
			&i.Score,
			&i.Wpm,
			&i.Raw,
			&i.Acc,
			&i.Grade,
			&i.Mods,
			&i.QuoteSource,
			&i.AchievedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProfileStreaks = `-- name: GetProfileStreaks :one
WITH days AS (SELECT DISTINCT (created_at AT TIME ZONE 'UTC')::date AS day
              FROM runs WHERE user_id = $1),
     islands AS (SELECT day,
                        day - (row_number() OVER (ORDER BY day))::int AS anchor
                 FROM days),
     lengths AS (SELECT count(*)::int AS len, max(day) AS last_day
                 FROM islands GROUP BY anchor)
SELECT coalesce(max(len), 0)::int                                        AS best,
       coalesce(max(len) FILTER (WHERE last_day >= $2::date - 1),
                0)::int                                                   AS current
FROM lengths
`

type GetProfileStreaksParams struct {
	UserID uuid.UUID
	Today  time.Time
}

type GetProfileStreaksRow struct {
	Best    int32
	Current int32
}

// Consecutive-day streaks over the days the user PLAYED (runs-based — logins
// are not tracked, by design; docs/PROFILE.md). Classic gaps-and-islands: a
// run of consecutive days shares one anchor (day - row_number). `current` is
// the island still alive relative to the caller-supplied "today" (UTC): its
// last day is today or yesterday — yesterday keeps the streak alive until the
// end of today. At most one island can satisfy that predicate, so the FILTER
// picks the island, not a maximum over several.
func (q *Queries) GetProfileStreaks(ctx context.Context, arg GetProfileStreaksParams) (GetProfileStreaksRow, error) {
	row := q.db.QueryRow(ctx, getProfileStreaks, arg.UserID, arg.Today)
	var i GetProfileStreaksRow
	err := row.Scan(&i.Best, &i.Current)
	return i, err
}

const getProfileTimeseries = `-- name: GetProfileTimeseries :many
SELECT (created_at AT TIME ZONE 'UTC')::date                        AS day,
       coalesce(sum((server_metrics ->> 'durationSec')::float8 * 1000)
                FILTER (WHERE status = 'accepted'), 0)::bigint      AS time_ms,
       coalesce(avg((server_metrics ->> 'wpm')::float8)
                FILTER (WHERE status = 'accepted'), 0)::float8      AS avg_wpm,
       coalesce(avg((server_metrics ->> 'accuracy')::float8)
                FILTER (WHERE status = 'accepted'), 0)::float8      AS avg_acc
FROM runs
WHERE user_id = $1 AND created_at >= $2 AND created_at < $3
GROUP BY 1
ORDER BY 1
`

type GetProfileTimeseriesParams struct {
	UserID      uuid.UUID
	CreatedAt   time.Time
	CreatedAt_2 time.Time
}

type GetProfileTimeseriesRow struct {
	Day    time.Time
	TimeMs int64
	AvgWpm float64
	AvgAcc float64
}

// Per-day chart series inside [from, to): time typing (accepted, verified
// durations), and the day's average wpm / accuracy over accepted runs.
func (q *Queries) GetProfileTimeseries(ctx context.Context, arg GetProfileTimeseriesParams) ([]GetProfileTimeseriesRow, error) {
	rows, err := q.db.Query(ctx, getProfileTimeseries, arg.UserID, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProfileTimeseriesRow{}
	for rows.Next() {
		var i GetProfileTimeseriesRow
		if err := rows.Scan(
			&i.Day,
			&i.TimeMs,
			&i.AvgWpm,
			&i.AvgAcc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProfileUser = `-- name: GetProfileUser :one

SELECT display_name, created_at FROM users WHERE id = $1
`

type GetProfileUserRow struct {
	DisplayName string
	CreatedAt   time.Time
}

// Profile aggregates (docs/PROFILE.md): on-demand SQL over `runs`, computed at
// request time, cached nowhere. Every query here is scoped to ONE user and must
// stay index-driven off runs_user_id_created_at_idx (or, for the PB cards,
// leaderboard_entries_user_idx) — the 100k-run perf suite pins the plans.
//
// Two aggregation rules, stated once (and asserted by tests):
//   - METRIC aggregates (wpm/raw/acc/consistency, estimated words) read
//     ACCEPTED runs only — the server-verified numbers in server_metrics.
//   - COUNTERS read every submitted run regardless of verdict (a flagged run
//     was still played), and tests_started additionally folds in the
//     client-reported restart counts: started = count(*) + sum(restarts).
func (q *Queries) GetProfileUser(ctx context.Context, id uuid.UUID) (GetProfileUserRow, error) {
	row := q.db.QueryRow(ctx, getProfileUser, id)
	var i GetProfileUserRow
	err := row.Scan(&i.DisplayName, &i.CreatedAt)
	return i, err
}

const getProfileWpmPerHour = `-- name: GetProfileWpmPerHour :one
WITH days AS (SELECT (created_at AT TIME ZONE 'UTC')::date AS day,
                     avg((server_metrics ->> 'wpm')::float8)          AS wpm,
                     sum((server_metrics ->> 'durationSec')::float8)  AS secs
              FROM runs
              WHERE user_id = $1 AND status = 'accepted'
                AND created_at >= $2 AND created_at < $3
              GROUP BY 1),
     pts AS (SELECT wpm, sum(secs) OVER (ORDER BY day) / 3600.0 AS hours
             FROM days)
SELECT coalesce(regr_slope(wpm, hours), 0)::float8 AS wpm_per_hour
FROM pts
`

type GetProfileWpmPerHourParams struct {
	UserID      uuid.UUID
	CreatedAt   time.Time
	CreatedAt_2 time.Time
}

// The header stat "speed change per hour spent typing": an ordinary
// least-squares slope (regr_slope) of y = a day's average wpm over x = the
// cumulative hours of accepted typing inside the range at that day's end. The
// points are the DAY buckets, not the raw runs, for two reasons that agree:
// the chart the stat headlines is a daily series (a trend line through
// different points than the chart plots would be a different claim), and a
// windowed running sum over 100k raw rows is a sort that spills to disk at
// scale, while ≤366 day points sort in a page (the zone-9 plan check is what
// caught it). NULL (fewer than two days, or zero variance in x) collapses to
// 0 — the "no trend yet" answer.
func (q *Queries) GetProfileWpmPerHour(ctx context.Context, arg GetProfileWpmPerHourParams) (float64, error) {
	row := q.db.QueryRow(ctx, getProfileWpmPerHour, arg.UserID, arg.CreatedAt, arg.CreatedAt_2)
	var wpm_per_hour float64
	err := row.Scan(&wpm_per_hour)
	return wpm_per_hour, err
}
