// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package profiledb

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const getProfileActivity = `-- name: GetProfileActivity :many
SELECT (r.created_at AT TIME ZONE 'UTC')::date                        AS day,
       count(*)::int                                                AS tests,
       coalesce(sum((v.server_metrics ->> 'durationSec')::float8 * 1000)
                FILTER (WHERE r.status = 'accepted'), 0)::bigint      AS time_ms
FROM runs r
         LEFT JOIN run_verdicts v ON v.run_id = r.id AND v.user_id = r.user_id
WHERE r.user_id = $1 AND r.created_at >= $2
GROUP BY 1
ORDER BY 1
`

type GetProfileActivityParams struct {
	UserID    uuid.UUID
	CreatedAt time.Time
}

type GetProfileActivityRow struct {
	Day    time.Time
	Tests  int32
	TimeMs int64
}

// Daily buckets for the activity calendar: every submitted run counts as a
// test that day; the time column reads the server-verified durations that
// exist (accepted runs). Days with no runs are absent — the calendar renders
// the gaps itself.
func (q *Queries) GetProfileActivity(ctx context.Context, arg GetProfileActivityParams) ([]GetProfileActivityRow, error) {
	rows, err := q.db.Query(ctx, getProfileActivity, arg.UserID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProfileActivityRow{}
	for rows.Next() {
		var i GetProfileActivityRow
		if err := rows.Scan(&i.Day, &i.Tests, &i.TimeMs); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProfileCounts = `-- name: GetProfileCounts :one
SELECT count(*)::bigint                                            AS tests_completed,
       coalesce(sum(restarts_since_last_submit), 0)::bigint        AS restarts,
       coalesce(sum((v.server_metrics ->> 'durationSec')::float8 * 1000)
                FILTER (WHERE r.status = 'accepted'), 0)::bigint     AS time_typing_ms,
       coalesce(sum(((v.server_metrics -> 'chars' ->> 'correct')::float8
                   + (v.server_metrics -> 'chars' ->> 'incorrect')::float8
                   + (v.server_metrics -> 'chars' ->> 'extra')::float8
                   + (v.server_metrics ->> 'spaces')::float8) / 5)
                FILTER (WHERE r.status = 'accepted'), 0)::float8     AS estimated_words
FROM runs r
         LEFT JOIN run_verdicts v ON v.run_id = r.id AND v.user_id = r.user_id
WHERE r.user_id = $1
`

type GetProfileCountsRow struct {
	TestsCompleted int64
	Restarts       int64
	TimeTypingMs   int64
	EstimatedWords float64
}

// Counters + the two derived totals. time_typing_ms and estimated_words read
// server_metrics (accepted only): durationSec is the deadline-pinned duration
// the core measured, and the words estimate is the raw character volume
// (correct+incorrect+extra+spaces) over the conventional 5 chars/word.
func (q *Queries) GetProfileCounts(ctx context.Context, userID uuid.UUID) (GetProfileCountsRow, error) {
	row := q.db.QueryRow(ctx, getProfileCounts, userID)
	var i GetProfileCountsRow
	err := row.Scan(
		&i.TestsCompleted,
		&i.Restarts,
		&i.TimeTypingMs,
		&i.EstimatedWords,
	)
	return i, err
}

const getProfileDominantLang = `-- name: GetProfileDominantLang :one
SELECT lang
FROM runs
WHERE user_id = $1
GROUP BY lang
ORDER BY count(*) DESC, lang
LIMIT 1
`

// The user's most-played dictionary language — the heatmap's default layout
// comes from it. Ties break alphabetically so the answer is stable.
func (q *Queries) GetProfileDominantLang(ctx context.Context, userID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getProfileDominantLang, userID)
	var lang string
	err := row.Scan(&lang)
	return lang, err
}

const getProfileHistogram = `-- name: GetProfileHistogram :many
SELECT (floor((v.server_metrics ->> 'wpm')::float8 / 10) * 10)::int AS bucket,
       count(*)::int                                                AS tests
FROM runs r
         JOIN run_verdicts v ON v.run_id = r.id AND v.user_id = r.user_id
WHERE r.user_id = $1 AND r.status = 'accepted'
GROUP BY 1
ORDER BY 1
`

type GetProfileHistogramRow struct {
	Bucket int32
	Tests  int32
}

// Tests per 10-wpm bucket over accepted runs; `bucket` is the lower bound
// (60 covers [60, 70)).
func (q *Queries) GetProfileHistogram(ctx context.Context, userID uuid.UUID) ([]GetProfileHistogramRow, error) {
	rows, err := q.db.Query(ctx, getProfileHistogram, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProfileHistogramRow{}
	for rows.Next() {
		var i GetProfileHistogramRow
		if err := rows.Scan(&i.Bucket, &i.Tests); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProfileKeyboard = `-- name: GetProfileKeyboard :many
SELECT key_id, presses, errors, interval_sum_ms, interval_count
FROM user_keyboard_profile
WHERE user_id = $1
ORDER BY key_id
`

type GetProfileKeyboardRow struct {
	KeyID         string
	Presses       int64
	Errors        int64
	IntervalSumMs float64
	IntervalCount int64
}

// The keyboard heatmap read: the projection's rows, verbatim — aggregates the
// worker maintains at verdict time, never derived from logs at request time.
func (q *Queries) GetProfileKeyboard(ctx context.Context, userID uuid.UUID) ([]GetProfileKeyboardRow, error) {
	rows, err := q.db.Query(ctx, getProfileKeyboard, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProfileKeyboardRow{}
	for rows.Next() {
		var i GetProfileKeyboardRow
		if err := rows.Scan(
			&i.KeyID,
			&i.Presses,
			&i.Errors,
			&i.IntervalSumMs,
			&i.IntervalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProfileLanguages = `-- name: GetProfileLanguages :one
SELECT (coalesce(jsonb_agg(jsonb_build_object('lang', lang, 'tests', tests)
                           ORDER BY tests DESC, lang), '[]'::jsonb))::jsonb AS languages
FROM (SELECT lang, count(*)::int AS tests
      FROM runs WHERE user_id = $1
      GROUP BY lang) t
`

// Per-language play counts over every submitted run, as one jsonb document —
// ordered most-played first.
func (q *Queries) GetProfileLanguages(ctx context.Context, userID uuid.UUID) (json.RawMessage, error) {
	row := q.db.QueryRow(ctx, getProfileLanguages, userID)
	var languages json.RawMessage
	err := row.Scan(&languages)
	return languages, err
}

const getProfileLast10 = `-- name: GetProfileLast10 :one
SELECT coalesce(avg(t.wpm), 0)::float8         AS wpm_average,
       coalesce(avg(t.raw), 0)::float8         AS raw_average,
       coalesce(avg(t.acc), 0)::float8         AS acc_average,
       coalesce(avg(t.consistency), 0)::float8 AS consistency_average
FROM (SELECT (v.server_metrics ->> 'wpm')::float8         AS wpm,
             (v.server_metrics ->> 'raw')::float8         AS raw,
             (v.server_metrics ->> 'accuracy')::float8    AS acc,
             (v.server_metrics ->> 'consistency')::float8 AS consistency
      FROM runs r
               JOIN run_verdicts v ON v.run_id = r.id AND v.user_id = r.user_id
      WHERE r.user_id = $1 AND r.status = 'accepted'
      ORDER BY r.created_at DESC, r.id DESC
      LIMIT 10) t
`

type GetProfileLast10Row struct {
	WpmAverage         float64
	RawAverage         float64
	AccAverage         float64
	ConsistencyAverage float64
}

// The same four metrics averaged over the LAST 10 accepted runs by date. The
// inner query walks (user_id, created_at DESC) newest-first and stops after
// ten accepted rows — no sort node, the index provides the order.
func (q *Queries) GetProfileLast10(ctx context.Context, userID uuid.UUID) (GetProfileLast10Row, error) {
	row := q.db.QueryRow(ctx, getProfileLast10, userID)
	var i GetProfileLast10Row
	err := row.Scan(
		&i.WpmAverage,
		&i.RawAverage,
		&i.AccAverage,
		&i.ConsistencyAverage,
	)
	return i, err
}

const getProfileMetricStats = `-- name: GetProfileMetricStats :one
SELECT coalesce(max((v.server_metrics ->> 'wpm')::float8), 0)::float8         AS wpm_highest,
       coalesce(avg((v.server_metrics ->> 'wpm')::float8), 0)::float8         AS wpm_average,
       coalesce(max((v.server_metrics ->> 'raw')::float8), 0)::float8         AS raw_highest,
       coalesce(avg((v.server_metrics ->> 'raw')::float8), 0)::float8         AS raw_average,
       coalesce(max((v.server_metrics ->> 'accuracy')::float8), 0)::float8    AS acc_highest,
       coalesce(avg((v.server_metrics ->> 'accuracy')::float8), 0)::float8    AS acc_average,
       coalesce(max((v.server_metrics ->> 'consistency')::float8), 0)::float8 AS consistency_highest,
       coalesce(avg((v.server_metrics ->> 'consistency')::float8), 0)::float8 AS consistency_average
FROM runs r
         JOIN run_verdicts v ON v.run_id = r.id AND v.user_id = r.user_id
WHERE r.user_id = $1 AND r.status = 'accepted'
`

type GetProfileMetricStatsRow struct {
	WpmHighest         float64
	WpmAverage         float64
	RawHighest         float64
	RawAverage         float64
	AccHighest         float64
	AccAverage         float64
	ConsistencyHighest float64
	ConsistencyAverage float64
}

// highest / average for the four profile metrics, over accepted runs.
func (q *Queries) GetProfileMetricStats(ctx context.Context, userID uuid.UUID) (GetProfileMetricStatsRow, error) {
	row := q.db.QueryRow(ctx, getProfileMetricStats, userID)
	var i GetProfileMetricStatsRow
	err := row.Scan(
		&i.WpmHighest,
		&i.WpmAverage,
		&i.RawHighest,
		&i.RawAverage,
		&i.AccHighest,
		&i.AccAverage,
		&i.ConsistencyHighest,
		&i.ConsistencyAverage,
	)
	return i, err
}

const getProfilePBs = `-- name: GetProfilePBs :many
SELECT bucket_key, run_id, score, wpm::float8 AS wpm, raw::float8 AS raw,
       acc::float8 AS acc, grade, mods, quote_source, achieved_at
FROM leaderboard_entries
WHERE user_id = $1
ORDER BY achieved_at DESC
`

type GetProfilePBsRow struct {
	BucketKey   string
	RunID       uuid.UUID
	Score       int64
	Wpm         float64
	Raw         float64
	Acc         float64
	Grade       string
	Mods        json.RawMessage
	QuoteSource *string
	AchievedAt  time.Time
}

// The PB cards: leaderboard_entries IS the per-bucket personal-best store (one
// row per player per bucket, projected from accepted runs), so this is a read,
// not a computation. Own-profile view — deliberately the raw entries table,
// not the ban-filtered leaderboard_rows: a player's own bests are their own
// data, and this surface is session-scoped to its owner.
func (q *Queries) GetProfilePBs(ctx context.Context, userID uuid.UUID) ([]GetProfilePBsRow, error) {
	rows, err := q.db.Query(ctx, getProfilePBs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProfilePBsRow{}
	for rows.Next() {
		var i GetProfilePBsRow
		if err := rows.Scan(
			&i.BucketKey,
			&i.RunID,
			&i.Score,
			&i.Wpm,
			&i.Raw,
			&i.Acc,
			&i.Grade,
			&i.Mods,
			&i.QuoteSource,
			&i.AchievedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProfileStreaks = `-- name: GetProfileStreaks :one
WITH days AS (SELECT DISTINCT (created_at AT TIME ZONE 'UTC')::date AS day
              FROM runs WHERE user_id = $1),
     islands AS (SELECT day,
                        day - (row_number() OVER (ORDER BY day))::int AS anchor
                 FROM days),
     lengths AS (SELECT count(*)::int AS len, max(day) AS last_day
                 FROM islands GROUP BY anchor)
SELECT coalesce(max(len), 0)::int                                        AS best,
       coalesce(max(len) FILTER (WHERE last_day >= $2::date - 1),
                0)::int                                                   AS current
FROM lengths
`

type GetProfileStreaksParams struct {
	UserID uuid.UUID
	Today  time.Time
}

type GetProfileStreaksRow struct {
	Best    int32
	Current int32
}

// Consecutive-day streaks over the days the user PLAYED (runs-based — logins
// are not tracked, by design; docs/PROFILE.md). Classic gaps-and-islands: a
// run of consecutive days shares one anchor (day - row_number). `current` is
// the island still alive relative to the caller-supplied "today" (UTC): its
// last day is today or yesterday — yesterday keeps the streak alive until the
// end of today. At most one island can satisfy that predicate, so the FILTER
// picks the island, not a maximum over several.
func (q *Queries) GetProfileStreaks(ctx context.Context, arg GetProfileStreaksParams) (GetProfileStreaksRow, error) {
	row := q.db.QueryRow(ctx, getProfileStreaks, arg.UserID, arg.Today)
	var i GetProfileStreaksRow
	err := row.Scan(&i.Best, &i.Current)
	return i, err
}

const getProfileTimeseries = `-- name: GetProfileTimeseries :many
SELECT (r.created_at AT TIME ZONE 'UTC')::date                        AS day,
       coalesce(sum((v.server_metrics ->> 'durationSec')::float8 * 1000)
                FILTER (WHERE r.status = 'accepted'), 0)::bigint      AS time_ms,
       coalesce(avg((v.server_metrics ->> 'wpm')::float8)
                FILTER (WHERE r.status = 'accepted'), 0)::float8      AS avg_wpm,
       coalesce(avg((v.server_metrics ->> 'accuracy')::float8)
                FILTER (WHERE r.status = 'accepted'), 0)::float8      AS avg_acc
FROM runs r
         LEFT JOIN run_verdicts v ON v.run_id = r.id AND v.user_id = r.user_id
WHERE r.user_id = $1 AND r.created_at >= $2 AND r.created_at < $3
GROUP BY 1
ORDER BY 1
`

type GetProfileTimeseriesParams struct {
	UserID      uuid.UUID
	CreatedAt   time.Time
	CreatedAt_2 time.Time
}

type GetProfileTimeseriesRow struct {
	Day    time.Time
	TimeMs int64
	AvgWpm float64
	AvgAcc float64
}

// Per-day chart series inside [from, to): time typing (accepted, verified
// durations), and the day's average wpm / accuracy over accepted runs.
func (q *Queries) GetProfileTimeseries(ctx context.Context, arg GetProfileTimeseriesParams) ([]GetProfileTimeseriesRow, error) {
	rows, err := q.db.Query(ctx, getProfileTimeseries, arg.UserID, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProfileTimeseriesRow{}
	for rows.Next() {
		var i GetProfileTimeseriesRow
		if err := rows.Scan(
			&i.Day,
			&i.TimeMs,
			&i.AvgWpm,
			&i.AvgAcc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProfileUser = `-- name: GetProfileUser :one

SELECT display_name, created_at FROM users WHERE id = $1
`

type GetProfileUserRow struct {
	DisplayName string
	CreatedAt   time.Time
}

// Profile aggregates (docs/PROFILE.md): on-demand SQL over `runs`, computed at
// request time, cached nowhere. Every query here is scoped to ONE user and must
// stay index-driven off runs_user_id_created_at_idx (or, for the PB cards,
// leaderboard_entries_user_idx) — the 100k-run perf suite pins the plans.
//
// Two aggregation rules, stated once (and asserted by tests):
//   - METRIC aggregates (wpm/raw/acc/consistency, estimated words) read
//     ACCEPTED runs only — the server-verified numbers in server_metrics,
//     which since 00019 live on the run_verdicts satellite (1:1 by run_id;
//     LEFT JOIN where the base set includes unjudged runs, INNER where
//     status = 'accepted' already implies the verdict row exists). Every join
//     carries the redundant-looking `v.user_id = r.user_id`: it is what lets
//     the planner propagate the $1 equality onto run_verdicts and drive BOTH
//     sides through player-scoped indexes (run_verdicts_user_idx) instead of
//     hashing the whole verdict table — the zone-9 plan pins are the test.
//   - COUNTERS read every submitted run regardless of verdict (a flagged run
//     was still played), and tests_started additionally folds in the
//     client-reported restart counts: started = count(*) + sum(restarts).
func (q *Queries) GetProfileUser(ctx context.Context, id uuid.UUID) (GetProfileUserRow, error) {
	row := q.db.QueryRow(ctx, getProfileUser, id)
	var i GetProfileUserRow
	err := row.Scan(&i.DisplayName, &i.CreatedAt)
	return i, err
}

const getProfileWpmPerHour = `-- name: GetProfileWpmPerHour :one
WITH raw AS MATERIALIZED (
        SELECT (r.created_at AT TIME ZONE 'UTC')::date        AS day,
               (v.server_metrics ->> 'wpm')::float8         AS wpm,
               (v.server_metrics ->> 'durationSec')::float8 AS secs
        FROM runs r
                 JOIN run_verdicts v ON v.run_id = r.id AND v.user_id = r.user_id
        WHERE r.user_id = $1 AND r.status = 'accepted'
          AND r.created_at >= $2 AND r.created_at < $3),
     days AS (SELECT day, avg(wpm) AS wpm, sum(secs) AS secs
              FROM raw
              GROUP BY 1),
     pts AS (SELECT wpm, sum(secs) OVER (ORDER BY day) / 3600.0 AS hours
             FROM days)
SELECT coalesce(regr_slope(wpm, hours), 0)::float8 AS wpm_per_hour
FROM pts
`

type GetProfileWpmPerHourParams struct {
	UserID      uuid.UUID
	CreatedAt   time.Time
	CreatedAt_2 time.Time
}

// The header stat "speed change per hour spent typing": an ordinary
// least-squares slope (regr_slope) of y = a day's average wpm over x = the
// cumulative hours of accepted typing inside the range at that day's end. The
// points are the DAY buckets, not the raw runs, for two reasons that agree:
// the chart the stat headlines is a daily series (a trend line through
// different points than the chart plots would be a different claim), and a
// windowed running sum over 100k raw rows is a sort that spills to disk at
// scale, while ≤366 day points sort in a page (the zone-9 plan check is what
// caught it). NULL (fewer than two days, or zero variance in x) collapses to
// 0 — the "no trend yet" answer.
//
// `raw` is MATERIALIZED on purpose: it narrows each tuple to (day, wpm, secs)
// BEFORE the grouping sort. Without the fence the planner flattens the CTE
// and sorts rows still carrying the whole server_metrics document — ~200
// bytes each — which at 100k accepted runs is exactly the disk-spilling sort
// the day-bucket design exists to avoid (the zone-9 spill check caught that
// too, when 00019 moved the metrics behind a join).
func (q *Queries) GetProfileWpmPerHour(ctx context.Context, arg GetProfileWpmPerHourParams) (float64, error) {
	row := q.db.QueryRow(ctx, getProfileWpmPerHour, arg.UserID, arg.CreatedAt, arg.CreatedAt_2)
	var wpm_per_hour float64
	err := row.Scan(&wpm_per_hour)
	return wpm_per_hour, err
}

const getPublicProfilePBs = `-- name: GetPublicProfilePBs :many
SELECT bucket_key, run_id, score, wpm::float8 AS wpm, raw::float8 AS raw,
       acc::float8 AS acc, grade, mods, quote_source, achieved_at
FROM leaderboard_entries e
WHERE e.user_id = $1
  AND NOT EXISTS (SELECT 1 FROM active_bans b WHERE b.user_id = e.user_id)
ORDER BY achieved_at DESC
`

type GetPublicProfilePBsRow struct {
	BucketKey   string
	RunID       uuid.UUID
	Score       int64
	Wpm         float64
	Raw         float64
	Acc         float64
	Grade       string
	Mods        json.RawMessage
	QuoteSource *string
	AchievedAt  time.Time
}

// The PB cards as a STRANGER may see them: the same entries read as
// GetProfilePBs, but through the ban predicate the boards read through. The
// session-scoped read deliberately skips it (a player's own bests are their
// own data); a public surface showing a banned player's records would leak
// what every board hides. leaderboard_rows is not used here only because the
// view does not carry quote_source; the predicate is the same active_bans
// object, so the two cannot drift.
func (q *Queries) GetPublicProfilePBs(ctx context.Context, userID uuid.UUID) ([]GetPublicProfilePBsRow, error) {
	rows, err := q.db.Query(ctx, getPublicProfilePBs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPublicProfilePBsRow{}
	for rows.Next() {
		var i GetPublicProfilePBsRow
		if err := rows.Scan(
			&i.BucketKey,
			&i.RunID,
			&i.Score,
			&i.Wpm,
			&i.Raw,
			&i.Acc,
			&i.Grade,
			&i.Mods,
			&i.QuoteSource,
			&i.AchievedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPublicProfileRunsAfter = `-- name: GetPublicProfileRunsAfter :many
SELECT r.id, r.mode, r.duration_ms, r.word_count, r.lang,
       v.server_metrics, v.server_score, r.created_at,
       (jsonb_strip_nulls(jsonb_build_object(
           'grade',       run_grade((v.server_metrics ->> 'accuracy')::numeric),
           'consistency', (v.server_metrics ->> 'consistency')::float8,
           'chars',       v.server_metrics -> 'chars',
           'quoteId',     run_quote_id(r.setup),
           'adoptedFromRunId', run_adopted_from(r.setup),
           'mods',        run_mods(r.setup))))::jsonb AS derived
FROM runs r
         JOIN run_verdicts v ON v.run_id = r.id AND v.user_id = r.user_id
WHERE r.user_id = $1
  AND r.status = 'accepted'
  AND NOT EXISTS (SELECT 1 FROM active_bans b WHERE b.user_id = r.user_id)
  AND r.created_at <= $2
  AND (r.created_at < $2 OR (r.created_at = $2 AND r.id < $3))
ORDER BY r.created_at DESC, r.id DESC
LIMIT $4
`

type GetPublicProfileRunsAfterParams struct {
	UserID    uuid.UUID
	CreatedAt time.Time
	ID        uuid.UUID
	Limit     int32
}

type GetPublicProfileRunsAfterRow struct {
	ID            uuid.UUID
	Mode          string
	DurationMs    *int32
	WordCount     *int32
	Lang          string
	ServerMetrics []byte
	ServerScore   []byte
	CreatedAt     time.Time
	Derived       json.RawMessage
}

// Next public-history page after the (created_at, id) cursor — the same
// longhand row-value comparison, with the redundant-looking `<=` SEEK conjunct,
// as ListRunsAfter in internal/runs/queries.sql, and for the same measured
// reason (migration 00015's 3-column index provides the start condition).
func (q *Queries) GetPublicProfileRunsAfter(ctx context.Context, arg GetPublicProfileRunsAfterParams) ([]GetPublicProfileRunsAfterRow, error) {
	rows, err := q.db.Query(ctx, getPublicProfileRunsAfter,
		arg.UserID,
		arg.CreatedAt,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPublicProfileRunsAfterRow{}
	for rows.Next() {
		var i GetPublicProfileRunsAfterRow
		if err := rows.Scan(
			&i.ID,
			&i.Mode,
			&i.DurationMs,
			&i.WordCount,
			&i.Lang,
			&i.ServerMetrics,
			&i.ServerScore,
			&i.CreatedAt,
			&i.Derived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPublicProfileRunsFirst = `-- name: GetPublicProfileRunsFirst :many
SELECT r.id, r.mode, r.duration_ms, r.word_count, r.lang,
       v.server_metrics, v.server_score, r.created_at,
       (jsonb_strip_nulls(jsonb_build_object(
           'grade',       run_grade((v.server_metrics ->> 'accuracy')::numeric),
           'consistency', (v.server_metrics ->> 'consistency')::float8,
           'chars',       v.server_metrics -> 'chars',
           'quoteId',     run_quote_id(r.setup),
           'adoptedFromRunId', run_adopted_from(r.setup),
           'mods',        run_mods(r.setup))))::jsonb AS derived
FROM runs r
         JOIN run_verdicts v ON v.run_id = r.id AND v.user_id = r.user_id
WHERE r.user_id = $1
  AND r.status = 'accepted'
  AND NOT EXISTS (SELECT 1 FROM active_bans b WHERE b.user_id = r.user_id)
ORDER BY r.created_at DESC, r.id DESC
LIMIT $2
`

type GetPublicProfileRunsFirstParams struct {
	UserID uuid.UUID
	Limit  int32
}

type GetPublicProfileRunsFirstRow struct {
	ID            uuid.UUID
	Mode          string
	DurationMs    *int32
	WordCount     *int32
	Lang          string
	ServerMetrics []byte
	ServerScore   []byte
	CreatedAt     time.Time
	Derived       json.RawMessage
}

// First page of a profile's PUBLIC run history. The WHERE clause is the board
// surface's visibility rule, spelled the same way as the public replay pair in
// internal/runs/queries.sql: only ACCEPTED runs, and none at all while the
// owner is banned (active_bans is THE ban/expiry predicate — docs/MODERATION.md).
// Whether the profile answers a stranger at all is the handler's 403, decided
// before this query runs; per-run visibility is decided here, in SQL, so no
// new code path can reach a hidden run.
//
// The column list is an ALLOWLIST, deliberately narrower than the owner's own
// feed: no client-reported numbers, no validation trail, no setup snapshot, no
// restart counter. server_metrics/server_score and the derived cells are
// exactly what the public replay route already serves per run.
func (q *Queries) GetPublicProfileRunsFirst(ctx context.Context, arg GetPublicProfileRunsFirstParams) ([]GetPublicProfileRunsFirstRow, error) {
	rows, err := q.db.Query(ctx, getPublicProfileRunsFirst, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPublicProfileRunsFirstRow{}
	for rows.Next() {
		var i GetPublicProfileRunsFirstRow
		if err := rows.Scan(
			&i.ID,
			&i.Mode,
			&i.DurationMs,
			&i.WordCount,
			&i.Lang,
			&i.ServerMetrics,
			&i.ServerScore,
			&i.CreatedAt,
			&i.Derived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPublicProfileUser = `-- name: GetPublicProfileUser :one
SELECT id, display_name, created_at, profile_public, keyboard_public
FROM users
WHERE display_name = $1
`

type GetPublicProfileUserRow struct {
	ID             uuid.UUID
	DisplayName    string
	CreatedAt      time.Time
	ProfilePublic  bool
	KeyboardPublic bool
}

// The public surface's name resolution (docs/PROFILE.md, "Public profiles"):
// display_name is citext UNIQUE, so the lookup is case-insensitive exactly the
// way registration's uniqueness is. Nothing else about the account rides along
// — the public payloads are explicit allowlists, and this row is where the
// allowlist for the header STOPS.
func (q *Queries) GetPublicProfileUser(ctx context.Context, displayName string) (GetPublicProfileUserRow, error) {
	row := q.db.QueryRow(ctx, getPublicProfileUser, displayName)
	var i GetPublicProfileUserRow
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.CreatedAt,
		&i.ProfilePublic,
		&i.KeyboardPublic,
	)
	return i, err
}

const searchUsersByName = `-- name: SearchUsersByName :many
SELECT u.display_name, u.created_at, u.profile_public
FROM users u
WHERE lower(u.display_name::text) LIKE '%' || $1::text || '%'
  AND NOT EXISTS (SELECT 1 FROM active_bans b WHERE b.user_id = u.id)
ORDER BY (lower(u.display_name::text) = $2::text) DESC,
         (lower(u.display_name::text) LIKE $1::text || '%') DESC,
         char_length(u.display_name::text),
         u.display_name
LIMIT $3
`

type SearchUsersByNameParams struct {
	Pattern string
	Needle  string
	Lim     int32
}

type SearchUsersByNameRow struct {
	DisplayName   string
	CreatedAt     time.Time
	ProfilePublic bool
}

// Player search (docs/PROFILE.md, "Search"). Two parameters carry one user
// input, on purpose:
//
//   - @pattern is the input lowercased AND escaped for LIKE. '_' is both a
//     legal display_name character (the 00001 CHECK allows [a-zA-Z0-9_.-])
//     and a LIKE wildcard, so an unescaped search for "foo_bar" would also
//     match "fooXbar" — a wrong result, not merely a loose one.
//   - @needle is the same input lowercased but NOT escaped. It feeds only the
//     exact-match ranking term, which compares strings rather than patterns
//     and would be broken by the escaping the pattern needs.
//
// Ranking is spelled out rather than delegated to pg_trgm's similarity():
// exact match, then prefix, then shortest name, then alphabetical. similarity()
// would order results by a number the searcher cannot predict, and it is noisy
// over 3-20 character handles; this ordering is one a user can reconstruct by
// looking at it. The alphabetical tail is what makes two identical requests
// return the same page — length alone leaves ties, and a search box that
// reshuffles under the cursor reads as broken.
//
// Banned accounts are absent: active_bans is the same predicate every
// leaderboard and the public run history read through (docs/MODERATION.md).
// Search is a discovery surface, so it hides exactly what the boards hide,
// while /users/{name} keeps answering 200 for a banned name — the header route
// has never been the thing that hides a ban.
//
// CLOSED profiles ARE returned. A closed profile is still ranked on the boards
// under its own name and its header still answers 200, so making it unfindable
// by that name would contradict "closed is a state, not a 404" (00018) without
// concealing anything the boards do not already publish. The row carries
// profile_public so the client can render the closed state instead of
// promising a page that will 403.
func (q *Queries) SearchUsersByName(ctx context.Context, arg SearchUsersByNameParams) ([]SearchUsersByNameRow, error) {
	rows, err := q.db.Query(ctx, searchUsersByName, arg.Pattern, arg.Needle, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchUsersByNameRow{}
	for rows.Next() {
		var i SearchUsersByNameRow
		if err := rows.Scan(&i.DisplayName, &i.CreatedAt, &i.ProfilePublic); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
