// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package replaydb

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type AuthIdentity struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	Provider        string
	ProviderSubject string
	Email           *string
	EmailVerified   bool
	CreatedAt       time.Time
}

type EmailToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Purpose   string
	TokenHash []byte
	ExpiresAt time.Time
	UsedAt    *time.Time
	CreatedAt time.Time
}

type Match struct {
	ID        string
	RoomCode  string
	Name      string
	Settings  json.RawMessage
	Freemods  json.RawMessage
	Seed      int64
	DictHash  string
	Lang      string
	GoAt      time.Time
	EndedAt   time.Time
	CreatedAt time.Time
}

type MatchRun struct {
	ID          uuid.UUID
	MatchID     string
	PlayerID    string
	Nick        string
	UserID      *uuid.UUID
	Freemods    json.RawMessage
	Log         []byte
	BatchCount  int32
	FinalStatus string
	CreatedAt   time.Time
}

type Run struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	Mode          string
	DurationMs    *int32
	WordCount     *int32
	Lang          string
	Seed          int64
	DictHash      string
	Setup         json.RawMessage
	ClientMetrics json.RawMessage
	ClientScore   json.RawMessage
	ScoreVersion  int16
	Status        string
	Log           []byte
	LogBytes      int32
	CreatedAt     time.Time
	ServerMetrics []byte
	ServerScore   []byte
	Validation    []byte
	BundleSha     *string
	ValidatedAt   *time.Time
	Attempts      int16
	LastError     *string
	PolicyVersion *int16
}

type Session struct {
	ID         uuid.UUID
	TokenHash  []byte
	UserID     uuid.UUID
	CreatedAt  time.Time
	ExpiresAt  time.Time
	LastSeenAt time.Time
}

type User struct {
	ID          uuid.UUID
	DisplayName string
	CreatedAt   time.Time
}

type UserCredential struct {
	UserID       uuid.UUID
	Argon2idHash string
	UpdatedAt    time.Time
}
