// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package replaydb

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const applyReplayDecision = `-- name: ApplyReplayDecision :exec
UPDATE runs
SET status         = $1,
    server_metrics = $2,
    server_score   = $3,
    validation     = $4,
    bundle_sha     = $5,
    attempts       = $6,
    last_error     = NULLIF($7::text, ''),
    validated_at   = now()
WHERE id = $8
`

type ApplyReplayDecisionParams struct {
	Status        string
	ServerMetrics []byte
	ServerScore   []byte
	Validation    []byte
	BundleSha     *string
	Attempts      int16
	LastError     string
	ID            uuid.UUID
}

// Record one verdict. client_metrics / client_score are deliberately untouched:
// the client's numbers and the server's sit side by side forever, because the
// pair IS the evidence a mismatch is judged on.
func (q *Queries) ApplyReplayDecision(ctx context.Context, arg ApplyReplayDecisionParams) error {
	_, err := q.db.Exec(ctx, applyReplayDecision,
		arg.Status,
		arg.ServerMetrics,
		arg.ServerScore,
		arg.Validation,
		arg.BundleSha,
		arg.Attempts,
		arg.LastError,
		arg.ID,
	)
	return err
}

const claimPendingRuns = `-- name: ClaimPendingRuns :many

SELECT id, seed, dict_hash, score_version, setup, client_metrics, client_score,
       log, attempts
FROM runs
WHERE status = 'pending'
ORDER BY created_at
FOR UPDATE SKIP LOCKED
LIMIT $1
`

type ClaimPendingRunsRow struct {
	ID            uuid.UUID
	Seed          int64
	DictHash      string
	ScoreVersion  int16
	Setup         json.RawMessage
	ClientMetrics json.RawMessage
	ClientScore   json.RawMessage
	Log           []byte
	Attempts      int16
}

// Replay worker queue (docs/REPLAY.md). Two statements, both executed inside the
// SAME transaction: the claim takes the row locks, the decision writes the
// verdict, and the commit releases both together.
// The queue scan. FOR UPDATE SKIP LOCKED lets N workers share one queue with no
// broker and no 'processing' status: a row another worker already holds is
// stepped over, and a worker that dies rolls its rows straight back to
// claimable. Oldest first, so nothing starves. Uses runs_pending_idx.
func (q *Queries) ClaimPendingRuns(ctx context.Context, limit int32) ([]ClaimPendingRunsRow, error) {
	rows, err := q.db.Query(ctx, claimPendingRuns, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimPendingRunsRow{}
	for rows.Next() {
		var i ClaimPendingRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.Seed,
			&i.DictHash,
			&i.ScoreVersion,
			&i.Setup,
			&i.ClientMetrics,
			&i.ClientScore,
			&i.Log,
			&i.Attempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
