// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package replaydb

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const applyReplayDecision = `-- name: ApplyReplayDecision :exec
UPDATE runs
SET status         = $1,
    server_metrics = $2,
    server_score   = $3,
    validation     = $4,
    bundle_sha     = $5,
    policy_version = $6,
    attempts       = $7,
    last_error     = NULLIF($8::text, ''),
    validated_at   = now()
WHERE id = $9
`

type ApplyReplayDecisionParams struct {
	Status        string
	ServerMetrics []byte
	ServerScore   []byte
	Validation    []byte
	BundleSha     *string
	PolicyVersion *int16
	Attempts      int16
	LastError     string
	ID            uuid.UUID
}

// Record one verdict. client_metrics / client_score are deliberately untouched:
// the client's numbers and the server's sit side by side forever, because the
// pair IS the evidence a mismatch is judged on. bundle_sha and policy_version
// together say which code and which rules produced this row.
func (q *Queries) ApplyReplayDecision(ctx context.Context, arg ApplyReplayDecisionParams) error {
	_, err := q.db.Exec(ctx, applyReplayDecision,
		arg.Status,
		arg.ServerMetrics,
		arg.ServerScore,
		arg.Validation,
		arg.BundleSha,
		arg.PolicyVersion,
		arg.Attempts,
		arg.LastError,
		arg.ID,
	)
	return err
}

const claimPendingRuns = `-- name: ClaimPendingRuns :many

SELECT id, seed, dict_hash, score_version, setup, client_metrics, client_score,
       log, attempts, created_at
FROM runs
WHERE status = 'pending'
ORDER BY created_at
FOR UPDATE SKIP LOCKED
LIMIT $1
`

type ClaimPendingRunsRow struct {
	ID            uuid.UUID
	Seed          int64
	DictHash      string
	ScoreVersion  int16
	Setup         json.RawMessage
	ClientMetrics json.RawMessage
	ClientScore   json.RawMessage
	Log           []byte
	Attempts      int16
	CreatedAt     time.Time
}

// Replay worker queue + revalidation (docs/REPLAY.md). The claim and the
// decision are executed inside the SAME transaction: the claim takes the row
// locks, the decision writes the verdict, and the commit releases both together.
// The queue scan. FOR UPDATE SKIP LOCKED lets N workers share one queue with no
// broker and no 'processing' status: a row another worker already holds is
// stepped over, and a worker that dies rolls its rows straight back to
// claimable. Oldest first, so nothing starves. Uses runs_pending_idx.
//
// created_at rides along because the judgement depends on it: the canary
// detectors are armed per run against the canary epoch (docs/REPLAY.md), and a
// run created before the canary-rendering client shipped must be judged exactly
// as it was. It is an already-selected column of the same row, so carrying it
// costs nothing.
func (q *Queries) ClaimPendingRuns(ctx context.Context, limit int32) ([]ClaimPendingRunsRow, error) {
	rows, err := q.db.Query(ctx, claimPendingRuns, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimPendingRunsRow{}
	for rows.Next() {
		var i ClaimPendingRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.Seed,
			&i.DictHash,
			&i.ScoreVersion,
			&i.Setup,
			&i.ClientMetrics,
			&i.ClientScore,
			&i.Log,
			&i.Attempts,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimStalePolicyRuns = `-- name: ClaimStalePolicyRuns :many
SELECT id, seed, dict_hash, score_version, setup, client_metrics, client_score,
       log, attempts, created_at
FROM runs
WHERE status <> 'pending'
  AND (policy_version IS NULL
       OR policy_version < $1
       OR bundle_sha IS DISTINCT FROM $2::text)
ORDER BY created_at
FOR UPDATE SKIP LOCKED
LIMIT $3
`

type ClaimStalePolicyRunsParams struct {
	PolicyVersion *int16
	BundleSha     string
	RowLimit      int32
}

type ClaimStalePolicyRunsRow struct {
	ID            uuid.UUID
	Seed          int64
	DictHash      string
	ScoreVersion  int16
	Setup         json.RawMessage
	ClientMetrics json.RawMessage
	ClientScore   json.RawMessage
	Log           []byte
	Attempts      int16
	CreatedAt     time.Time
}

// The revalidation scan: runs already judged, but by rules or by CODE that are
// no longer current. Two independent reasons to re-judge, because bundle_sha and
// policy_version answer different questions (docs/REPLAY.md, "Policy
// versioning"):
//
//	policy_version behind (or NULL, i.e. judged before the policy existed)
//	    the rules that turned the numbers into a status have moved
//	bundle_sha not the current one
//	    the code that produced the NUMBERS has moved, so the numbers on the row
//	    are the old bundle's and may disagree with what the client now computes
//
// Keying on policy_version alone left the second class stranded: a re-vendored
// bundle would flag honest runs as metric_mismatch and `make revalidate` would
// refuse to look at them, because their policy_version was already current.
//
// IS DISTINCT FROM, not <>, so a row judged before bundle_sha was recorded
// (NULL) is claimed rather than skipped by three-valued logic.
//
// Same locking discipline as the queue, so a revalidation pass and the worker
// can run at the same time without either seeing the other's rows. Uses
// runs_stale_policy_idx.
func (q *Queries) ClaimStalePolicyRuns(ctx context.Context, arg ClaimStalePolicyRunsParams) ([]ClaimStalePolicyRunsRow, error) {
	rows, err := q.db.Query(ctx, claimStalePolicyRuns, arg.PolicyVersion, arg.BundleSha, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimStalePolicyRunsRow{}
	for rows.Next() {
		var i ClaimStalePolicyRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.Seed,
			&i.DictHash,
			&i.ScoreVersion,
			&i.Setup,
			&i.ClientMetrics,
			&i.ClientScore,
			&i.Log,
			&i.Attempts,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsForCalibration = `-- name: ListRunsForCalibration :many
SELECT id, seed, dict_hash, score_version, setup, client_metrics, client_score,
       log, attempts, status, policy_version, created_at
FROM runs
WHERE status <> 'pending'
ORDER BY created_at
LIMIT $1
`

type ListRunsForCalibrationRow struct {
	ID            uuid.UUID
	Seed          int64
	DictHash      string
	ScoreVersion  int16
	Setup         json.RawMessage
	ClientMetrics json.RawMessage
	ClientScore   json.RawMessage
	Log           []byte
	Attempts      int16
	Status        string
	PolicyVersion *int16
	CreatedAt     time.Time
}

// Read-only sample for `make calibrate`: everything the decision needs, plus the
// status the run currently carries so a dry run can report what would change.
// No locking, no ordering surprises — oldest first, bounded by the caller.
func (q *Queries) ListRunsForCalibration(ctx context.Context, rowLimit int32) ([]ListRunsForCalibrationRow, error) {
	rows, err := q.db.Query(ctx, listRunsForCalibration, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRunsForCalibrationRow{}
	for rows.Next() {
		var i ListRunsForCalibrationRow
		if err := rows.Scan(
			&i.ID,
			&i.Seed,
			&i.DictHash,
			&i.ScoreVersion,
			&i.Setup,
			&i.ClientMetrics,
			&i.ClientScore,
			&i.Log,
			&i.Attempts,
			&i.Status,
			&i.PolicyVersion,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
