// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package replaydb

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const applyRunOutcome = `-- name: ApplyRunOutcome :exec
UPDATE runs
SET status     = $1,
    attempts   = $2,
    last_error = NULLIF($3::text, '')
WHERE id = $4
`

type ApplyRunOutcomeParams struct {
	Status    string
	Attempts  int16
	LastError string
	ID        uuid.UUID
}

// The lifecycle half of the same decision: status transition plus the queue's
// retry bookkeeping. Always executed in the same transaction as
// UpsertRunVerdict; the invariant "status <> 'pending' <=> a verdict row
// exists" is exactly the pair of these two statements committing together.
func (q *Queries) ApplyRunOutcome(ctx context.Context, arg ApplyRunOutcomeParams) error {
	_, err := q.db.Exec(ctx, applyRunOutcome,
		arg.Status,
		arg.Attempts,
		arg.LastError,
		arg.ID,
	)
	return err
}

const claimPendingRuns = `-- name: ClaimPendingRuns :many

SELECT id, seed, dict_hash, score_version, setup, client_metrics, client_score,
       log, attempts, created_at
FROM runs
WHERE status = 'pending'
ORDER BY created_at
FOR UPDATE SKIP LOCKED
LIMIT $1
`

type ClaimPendingRunsRow struct {
	ID            uuid.UUID
	Seed          int64
	DictHash      string
	ScoreVersion  int16
	Setup         json.RawMessage
	ClientMetrics json.RawMessage
	ClientScore   json.RawMessage
	Log           []byte
	Attempts      int16
	CreatedAt     time.Time
}

// Replay worker queue + revalidation (docs/REPLAY.md). The claim and the
// decision are executed inside the SAME transaction: the claim takes the row
// locks, the decision writes the verdict, and the commit releases both together.
//
// Since 00019 the verdict payload lives in run_verdicts (1:1 with runs, row
// exists <=> judged); runs keeps the lifecycle (status) and the queue's retry
// bookkeeping (attempts, last_error). A decision is therefore two statements —
// UpsertRunVerdict + ApplyRunOutcome — issued back to back in the claim's
// transaction, which is the same atomicity the old single UPDATE had.
// The queue scan. FOR UPDATE SKIP LOCKED lets N workers share one queue with no
// broker and no 'processing' status: a row another worker already holds is
// stepped over, and a worker that dies rolls its rows straight back to
// claimable. Oldest first, so nothing starves. Uses runs_pending_idx.
//
// created_at rides along because the judgement depends on it: the canary
// detectors are armed per run against the canary epoch (docs/REPLAY.md), and a
// run created before the canary-rendering client shipped must be judged exactly
// as it was. It is an already-selected column of the same row, so carrying it
// costs nothing.
func (q *Queries) ClaimPendingRuns(ctx context.Context, limit int32) ([]ClaimPendingRunsRow, error) {
	rows, err := q.db.Query(ctx, claimPendingRuns, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimPendingRunsRow{}
	for rows.Next() {
		var i ClaimPendingRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.Seed,
			&i.DictHash,
			&i.ScoreVersion,
			&i.Setup,
			&i.ClientMetrics,
			&i.ClientScore,
			&i.Log,
			&i.Attempts,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimStalePolicyRuns = `-- name: ClaimStalePolicyRuns :many
SELECT r.id, r.seed, r.dict_hash, r.score_version, r.setup, r.client_metrics,
       r.client_score, r.log, r.attempts, r.created_at
FROM runs r
         JOIN run_verdicts v ON v.run_id = r.id
WHERE v.policy_version IS NULL
   OR v.policy_version < $1
   OR v.bundle_sha IS DISTINCT FROM $2::text
ORDER BY r.created_at
FOR UPDATE OF r, v SKIP LOCKED
LIMIT $3
`

type ClaimStalePolicyRunsParams struct {
	PolicyVersion *int16
	BundleSha     string
	RowLimit      int32
}

type ClaimStalePolicyRunsRow struct {
	ID            uuid.UUID
	Seed          int64
	DictHash      string
	ScoreVersion  int16
	Setup         json.RawMessage
	ClientMetrics json.RawMessage
	ClientScore   json.RawMessage
	Log           []byte
	Attempts      int16
	CreatedAt     time.Time
}

// The revalidation scan: runs already judged, but by rules or by CODE that are
// no longer current. The join IS the "judged" predicate — a verdict row exists
// exactly for judged runs, so this claim walks the verdict table where it used
// to walk the status <> 'pending' partial index. Two independent reasons to
// re-judge, because bundle_sha and policy_version answer different questions
// (docs/REPLAY.md, "Policy versioning"):
//
//	policy_version behind (or NULL, i.e. judged before the policy existed)
//	    the rules that turned the numbers into a status have moved
//	bundle_sha not the current one
//	    the code that produced the NUMBERS has moved, so the numbers on the row
//	    are the old bundle's and may disagree with what the client now computes
//
// Keying on policy_version alone left the second class stranded: a re-vendored
// bundle would flag honest runs as metric_mismatch and `make revalidate` would
// refuse to look at them, because their policy_version was already current.
//
// IS DISTINCT FROM, not <>, so a row judged before bundle_sha was recorded
// (NULL) is claimed rather than skipped by three-valued logic.
//
// FOR UPDATE OF r, v: both halves of the run are locked, with the same SKIP
// LOCKED discipline as the queue, so a revalidation pass and the worker can run
// at the same time without either seeing the other's rows (their claims are
// disjoint anyway — a pending run has no verdict row to join).
func (q *Queries) ClaimStalePolicyRuns(ctx context.Context, arg ClaimStalePolicyRunsParams) ([]ClaimStalePolicyRunsRow, error) {
	rows, err := q.db.Query(ctx, claimStalePolicyRuns, arg.PolicyVersion, arg.BundleSha, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimStalePolicyRunsRow{}
	for rows.Next() {
		var i ClaimStalePolicyRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.Seed,
			&i.DictHash,
			&i.ScoreVersion,
			&i.Setup,
			&i.ClientMetrics,
			&i.ClientScore,
			&i.Log,
			&i.Attempts,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsForCalibration = `-- name: ListRunsForCalibration :many
SELECT r.id, r.seed, r.dict_hash, r.score_version, r.setup, r.client_metrics,
       r.client_score, r.log, r.attempts, r.status, v.policy_version,
       r.created_at
FROM runs r
         JOIN run_verdicts v ON v.run_id = r.id
ORDER BY r.created_at
LIMIT $1
`

type ListRunsForCalibrationRow struct {
	ID            uuid.UUID
	Seed          int64
	DictHash      string
	ScoreVersion  int16
	Setup         json.RawMessage
	ClientMetrics json.RawMessage
	ClientScore   json.RawMessage
	Log           []byte
	Attempts      int16
	Status        string
	PolicyVersion *int16
	CreatedAt     time.Time
}

// Read-only sample for `make calibrate`: everything the decision needs, plus
// the status and policy_version the run currently carries so a dry run can
// report what would change. The verdict join doubles as the "judged only"
// filter. No locking, no ordering surprises — oldest first, bounded by the
// caller.
func (q *Queries) ListRunsForCalibration(ctx context.Context, rowLimit int32) ([]ListRunsForCalibrationRow, error) {
	rows, err := q.db.Query(ctx, listRunsForCalibration, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRunsForCalibrationRow{}
	for rows.Next() {
		var i ListRunsForCalibrationRow
		if err := rows.Scan(
			&i.ID,
			&i.Seed,
			&i.DictHash,
			&i.ScoreVersion,
			&i.Setup,
			&i.ClientMetrics,
			&i.ClientScore,
			&i.Log,
			&i.Attempts,
			&i.Status,
			&i.PolicyVersion,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRunVerdict = `-- name: UpsertRunVerdict :exec
INSERT INTO run_verdicts (run_id, user_id, server_metrics, server_score,
                          validation, bundle_sha, policy_version, validated_at)
SELECT r.id, r.user_id, $1::jsonb, $2::jsonb,
       $3::jsonb, $4, $5, now()
FROM runs r
WHERE r.id = $6
ON CONFLICT (run_id) DO UPDATE SET
    server_metrics = excluded.server_metrics,
    server_score   = excluded.server_score,
    validation     = excluded.validation,
    bundle_sha     = excluded.bundle_sha,
    policy_version = excluded.policy_version,
    validated_at   = now()
`

type UpsertRunVerdictParams struct {
	ServerMetrics json.RawMessage
	ServerScore   json.RawMessage
	Validation    json.RawMessage
	BundleSha     *string
	PolicyVersion *int16
	RunID         uuid.UUID
}

// Record one verdict's payload. client_metrics / client_score on runs are
// deliberately untouched: the client's numbers and the server's sit side by
// side forever, because the pair IS the evidence a mismatch is judged on.
// bundle_sha and policy_version together say which code and which rules
// produced this row. The upsert is what makes revalidation a rewrite of the
// SAME verdict identity rather than a second one.
//
// user_id is sourced from the runs row right here (INSERT..SELECT), so the
// snapshot column cannot be miswritten by a caller and the Decision type
// never needs to carry it. On conflict it is left alone: it is immutable.
func (q *Queries) UpsertRunVerdict(ctx context.Context, arg UpsertRunVerdictParams) error {
	_, err := q.db.Exec(ctx, upsertRunVerdict,
		arg.ServerMetrics,
		arg.ServerScore,
		arg.Validation,
		arg.BundleSha,
		arg.PolicyVersion,
		arg.RunID,
	)
	return err
}
