// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package runsdb

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createRun = `-- name: CreateRun :one

INSERT INTO runs (
    user_id, mode, duration_ms, word_count, lang, seed, dict_hash,
    setup, client_metrics, client_score, score_version, log, log_bytes,
    restarts_since_last_submit
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
RETURNING id, status, created_at
`

type CreateRunParams struct {
	UserID                  uuid.UUID
	Mode                    string
	DurationMs              *int32
	WordCount               *int32
	Lang                    string
	Seed                    int64
	DictHash                string
	Setup                   json.RawMessage
	ClientMetrics           json.RawMessage
	ClientScore             json.RawMessage
	ScoreVersion            int16
	Log                     []byte
	LogBytes                int32
	RestartsSinceLastSubmit int32
}

type CreateRunRow struct {
	ID        uuid.UUID
	Status    string
	CreatedAt time.Time
}

// Queries for the runs domain. sqlc generates type-safe Go from these into
// internal/runs/runsdb. The gzip log blob is written once at ingestion and read
// back only through GetRunLog (the ?log=1 detail flag) and GetPublicReplayLog
// (the public log route); the summary queries deliberately never SELECT it.
func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (CreateRunRow, error) {
	row := q.db.QueryRow(ctx, createRun,
		arg.UserID,
		arg.Mode,
		arg.DurationMs,
		arg.WordCount,
		arg.Lang,
		arg.Seed,
		arg.DictHash,
		arg.Setup,
		arg.ClientMetrics,
		arg.ClientScore,
		arg.ScoreVersion,
		arg.Log,
		arg.LogBytes,
		arg.RestartsSinceLastSubmit,
	)
	var i CreateRunRow
	err := row.Scan(&i.ID, &i.Status, &i.CreatedAt)
	return i, err
}

const getPublicReplay = `-- name: GetPublicReplay :one
SELECT r.setup, v.server_metrics, v.server_score,
       run_grade((v.server_metrics ->> 'accuracy')::numeric)::text AS grade,
       r.mode, r.duration_ms, r.word_count, r.lang, r.seed, r.dict_hash,
       r.created_at, u.display_name
FROM runs r
         JOIN run_verdicts v ON v.run_id = r.id
         JOIN users u ON u.id = r.user_id
WHERE r.id = $1
  AND r.status = 'accepted'
  AND jsonb_typeof(v.server_metrics -> 'accuracy') = 'number'
  AND NOT EXISTS (SELECT 1 FROM active_bans b WHERE b.user_id = r.user_id)
  AND (u.profile_public OR EXISTS (SELECT 1 FROM leaderboard_entries e WHERE e.run_id = r.id))
`

type GetPublicReplayRow struct {
	Setup         json.RawMessage
	ServerMetrics []byte
	ServerScore   []byte
	Grade         string
	Mode          string
	DurationMs    *int32
	WordCount     *int32
	Lang          string
	Seed          int64
	DictHash      string
	CreatedAt     time.Time
	DisplayName   string
}

// Everything needed to describe someone else's run: the setup and the seed to
// regenerate the text, the dict_hash to verify the dictionary that regeneration
// is fed, and the server's own verdict numbers. The log is NOT here — it is a
// separate route (GetPublicReplayLog) so the stored gzip blob can go straight
// to the socket instead of being gunzipped into a JSON envelope
// (docs/PERFORMANCE.md, zone 6).
//
// seed and dict_hash are the same two columns the owner's authenticated summary
// already exposes (docs/RUNS.md); the word list is regenerated on the client
// from them, so the server never ships a word list it would then have to keep
// in sync with the core's generator.
//
// Four access rules are in the WHERE clause rather than in Go, so no caller can
// reach this data without them: the run must be ACCEPTED (a flagged, rejected
// or unjudged run is not a public artefact), its owner must not be banned, and
// — since public profiles — its owner's profile must be open OR the run must
// hold a leaderboard slot. The last disjunct is the boundary between profile
// privacy and the boards (docs/PROFILE.md, "Public profiles"): closing a
// profile hides the aggregated history page, never a result its owner put into
// a public ranking, so a board row's replay keeps working whatever the switch
// says. All failures return no row, which the handler renders as one
// indistinguishable 404 — a leaderboard must not leak who is under review.
func (q *Queries) GetPublicReplay(ctx context.Context, runID uuid.UUID) (GetPublicReplayRow, error) {
	row := q.db.QueryRow(ctx, getPublicReplay, runID)
	var i GetPublicReplayRow
	err := row.Scan(
		&i.Setup,
		&i.ServerMetrics,
		&i.ServerScore,
		&i.Grade,
		&i.Mode,
		&i.DurationMs,
		&i.WordCount,
		&i.Lang,
		&i.Seed,
		&i.DictHash,
		&i.CreatedAt,
		&i.DisplayName,
	)
	return i, err
}

const getPublicReplayLog = `-- name: GetPublicReplayLog :one
SELECT r.log
FROM runs r
         JOIN run_verdicts v ON v.run_id = r.id
         JOIN users u ON u.id = r.user_id
WHERE r.id = $1
  AND r.status = 'accepted'
  AND jsonb_typeof(v.server_metrics -> 'accuracy') = 'number'
  AND NOT EXISTS (SELECT 1 FROM active_bans b WHERE b.user_id = r.user_id)
  AND (u.profile_public OR EXISTS (SELECT 1 FROM leaderboard_entries e WHERE e.run_id = r.id))
`

// The stored gzip event log of one publicly watchable run, and nothing else, so
// the log route never re-reads the metadata it is not going to serve.
//
// The WHERE clause is the SAME FOUR RULES, spelled the same way, including the
// join to users: eligibility for the log must be eligibility for the metadata,
// character for character, or the two routes drift into two access matrices.
func (q *Queries) GetPublicReplayLog(ctx context.Context, runID uuid.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getPublicReplayLog, runID)
	var log []byte
	err := row.Scan(&log)
	return log, err
}

const getRun = `-- name: GetRun :one
SELECT r.id, r.mode, r.duration_ms, r.word_count, r.lang, r.seed, r.dict_hash,
       r.setup, r.client_metrics, r.client_score, r.score_version, r.status,
       v.server_metrics, v.server_score, v.validation, v.validated_at,
       r.log_bytes, r.restarts_since_last_submit, r.created_at,
       (jsonb_strip_nulls(jsonb_build_object(
           'grade',       run_grade((v.server_metrics ->> 'accuracy')::numeric),
           'consistency', (v.server_metrics ->> 'consistency')::float8,
           'chars',       v.server_metrics -> 'chars',
           'quoteId',     run_quote_id(r.setup),
           'adoptedFromRunId', run_adopted_from(r.setup),
           'mods',        run_mods(r.setup))))::jsonb AS derived
FROM runs r
         LEFT JOIN run_verdicts v ON v.run_id = r.id
WHERE r.id = $1 AND r.user_id = $2
`

type GetRunParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

type GetRunRow struct {
	ID                      uuid.UUID
	Mode                    string
	DurationMs              *int32
	WordCount               *int32
	Lang                    string
	Seed                    int64
	DictHash                string
	Setup                   json.RawMessage
	ClientMetrics           json.RawMessage
	ClientScore             json.RawMessage
	ScoreVersion            int16
	Status                  string
	ServerMetrics           []byte
	ServerScore             []byte
	Validation              []byte
	ValidatedAt             *time.Time
	LogBytes                int32
	RestartsSinceLastSubmit int32
	CreatedAt               time.Time
	Derived                 json.RawMessage
}

// One run's summary (no log payload), scoped to its owner.
func (q *Queries) GetRun(ctx context.Context, arg GetRunParams) (GetRunRow, error) {
	row := q.db.QueryRow(ctx, getRun, arg.ID, arg.UserID)
	var i GetRunRow
	err := row.Scan(
		&i.ID,
		&i.Mode,
		&i.DurationMs,
		&i.WordCount,
		&i.Lang,
		&i.Seed,
		&i.DictHash,
		&i.Setup,
		&i.ClientMetrics,
		&i.ClientScore,
		&i.ScoreVersion,
		&i.Status,
		&i.ServerMetrics,
		&i.ServerScore,
		&i.Validation,
		&i.ValidatedAt,
		&i.LogBytes,
		&i.RestartsSinceLastSubmit,
		&i.CreatedAt,
		&i.Derived,
	)
	return i, err
}

const getRunLog = `-- name: GetRunLog :one
SELECT log FROM runs
WHERE id = $1 AND user_id = $2
`

type GetRunLogParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// The gzip log blob for one run, scoped to its owner (the ?log=1 detail flag).
func (q *Queries) GetRunLog(ctx context.Context, arg GetRunLogParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getRunLog, arg.ID, arg.UserID)
	var log []byte
	err := row.Scan(&log)
	return log, err
}

const insertRunStatusOverride = `-- name: InsertRunStatusOverride :one
INSERT INTO run_status_overrides (run_id, from_status, to_status, reason, decided_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, run_id, from_status, to_status, reason, decided_by, decided_at
`

type InsertRunStatusOverrideParams struct {
	RunID      uuid.UUID
	FromStatus string
	ToStatus   string
	Reason     string
	DecidedBy  uuid.UUID
}

// Append the decision. One row per decision, never an upsert — see 00028.
func (q *Queries) InsertRunStatusOverride(ctx context.Context, arg InsertRunStatusOverrideParams) (RunStatusOverride, error) {
	row := q.db.QueryRow(ctx, insertRunStatusOverride,
		arg.RunID,
		arg.FromStatus,
		arg.ToStatus,
		arg.Reason,
		arg.DecidedBy,
	)
	var i RunStatusOverride
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.FromStatus,
		&i.ToStatus,
		&i.Reason,
		&i.DecidedBy,
		&i.DecidedAt,
	)
	return i, err
}

const listRunStatusOverrides = `-- name: ListRunStatusOverrides :many
SELECT o.id, o.run_id, o.from_status, o.to_status, o.reason,
       o.decided_by, u.display_name AS decided_by_name, o.decided_at
FROM run_status_overrides o
         JOIN users u ON u.id = o.decided_by
WHERE o.run_id = $1
ORDER BY o.decided_at DESC
`

type ListRunStatusOverridesRow struct {
	ID            uuid.UUID
	RunID         uuid.UUID
	FromStatus    string
	ToStatus      string
	Reason        string
	DecidedBy     uuid.UUID
	DecidedByName string
	DecidedAt     time.Time
}

// The audit read, newest first.
func (q *Queries) ListRunStatusOverrides(ctx context.Context, runID uuid.UUID) ([]ListRunStatusOverridesRow, error) {
	rows, err := q.db.Query(ctx, listRunStatusOverrides, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRunStatusOverridesRow{}
	for rows.Next() {
		var i ListRunStatusOverridesRow
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.FromStatus,
			&i.ToStatus,
			&i.Reason,
			&i.DecidedBy,
			&i.DecidedByName,
			&i.DecidedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsAfter = `-- name: ListRunsAfter :many
SELECT r.id, r.mode, r.duration_ms, r.word_count, r.lang, r.seed, r.dict_hash,
       r.setup, r.client_metrics, r.client_score, r.score_version, r.status,
       v.server_metrics, v.server_score, v.validation, v.validated_at,
       r.log_bytes, r.restarts_since_last_submit, r.created_at,
       (jsonb_strip_nulls(jsonb_build_object(
           'grade',       run_grade((v.server_metrics ->> 'accuracy')::numeric),
           'consistency', (v.server_metrics ->> 'consistency')::float8,
           'chars',       v.server_metrics -> 'chars',
           'quoteId',     run_quote_id(r.setup),
           'adoptedFromRunId', run_adopted_from(r.setup),
           'mods',        run_mods(r.setup))))::jsonb AS derived
FROM runs r
         LEFT JOIN run_verdicts v ON v.run_id = r.id
WHERE r.user_id = $1
  AND r.created_at <= $2
  AND (r.created_at < $2 OR (r.created_at = $2 AND r.id < $3))
ORDER BY r.created_at DESC, r.id DESC
LIMIT $4
`

type ListRunsAfterParams struct {
	UserID    uuid.UUID
	CreatedAt time.Time
	ID        uuid.UUID
	Limit     int32
}

type ListRunsAfterRow struct {
	ID                      uuid.UUID
	Mode                    string
	DurationMs              *int32
	WordCount               *int32
	Lang                    string
	Seed                    int64
	DictHash                string
	Setup                   json.RawMessage
	ClientMetrics           json.RawMessage
	ClientScore             json.RawMessage
	ScoreVersion            int16
	Status                  string
	ServerMetrics           []byte
	ServerScore             []byte
	Validation              []byte
	ValidatedAt             *time.Time
	LogBytes                int32
	RestartsSinceLastSubmit int32
	CreatedAt               time.Time
	Derived                 json.RawMessage
}

// Next page after the (created_at, id) cursor. The row-value comparison written
// out longhand keeps sqlc's type inference happy and matches the composite
// (created_at DESC, id DESC) ordering exactly. The redundant-looking
// `created_at <= $2` conjunct is the SEEK: the planner cannot derive a start
// condition from the OR form alone, so without it the cursor is a filter the
// index scan walks up to — linear in depth, measured at 66 ms by row 50 000 on
// the zone-9 fixture. With it, the scan starts at the cursor and the OR only
// trims the tie boundary (migration 00015 carries the matching 3-column
// index, which is also what retires the id-tiebreak Incremental Sort).
func (q *Queries) ListRunsAfter(ctx context.Context, arg ListRunsAfterParams) ([]ListRunsAfterRow, error) {
	rows, err := q.db.Query(ctx, listRunsAfter,
		arg.UserID,
		arg.CreatedAt,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRunsAfterRow{}
	for rows.Next() {
		var i ListRunsAfterRow
		if err := rows.Scan(
			&i.ID,
			&i.Mode,
			&i.DurationMs,
			&i.WordCount,
			&i.Lang,
			&i.Seed,
			&i.DictHash,
			&i.Setup,
			&i.ClientMetrics,
			&i.ClientScore,
			&i.ScoreVersion,
			&i.Status,
			&i.ServerMetrics,
			&i.ServerScore,
			&i.Validation,
			&i.ValidatedAt,
			&i.LogBytes,
			&i.RestartsSinceLastSubmit,
			&i.CreatedAt,
			&i.Derived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsFirst = `-- name: ListRunsFirst :many
SELECT r.id, r.mode, r.duration_ms, r.word_count, r.lang, r.seed, r.dict_hash,
       r.setup, r.client_metrics, r.client_score, r.score_version, r.status,
       v.server_metrics, v.server_score, v.validation, v.validated_at,
       r.log_bytes, r.restarts_since_last_submit, r.created_at,
       (jsonb_strip_nulls(jsonb_build_object(
           'grade',       run_grade((v.server_metrics ->> 'accuracy')::numeric),
           'consistency', (v.server_metrics ->> 'consistency')::float8,
           'chars',       v.server_metrics -> 'chars',
           'quoteId',     run_quote_id(r.setup),
           'adoptedFromRunId', run_adopted_from(r.setup),
           'mods',        run_mods(r.setup))))::jsonb AS derived
FROM runs r
         LEFT JOIN run_verdicts v ON v.run_id = r.id
WHERE r.user_id = $1
ORDER BY r.created_at DESC, r.id DESC
LIMIT $2
`

type ListRunsFirstParams struct {
	UserID uuid.UUID
	Limit  int32
}

type ListRunsFirstRow struct {
	ID                      uuid.UUID
	Mode                    string
	DurationMs              *int32
	WordCount               *int32
	Lang                    string
	Seed                    int64
	DictHash                string
	Setup                   json.RawMessage
	ClientMetrics           json.RawMessage
	ClientScore             json.RawMessage
	ScoreVersion            int16
	Status                  string
	ServerMetrics           []byte
	ServerScore             []byte
	Validation              []byte
	ValidatedAt             *time.Time
	LogBytes                int32
	RestartsSinceLastSubmit int32
	CreatedAt               time.Time
	Derived                 json.RawMessage
}

// First page of a user's runs, newest first. Keyset pagination continues via
// ListRunsAfter using the (created_at, id) of the last row. The verdict
// columns (server_metrics/server_score/validation/validated_at) come from the
// run_verdicts satellite (00019) through a LEFT JOIN: a pending run has no
// verdict row yet, and the join's NULLs are exactly the "not judged yet" the
// columns themselves used to carry.
//
// The trailing `derived` document carries the profile table's cells, lifted
// server-side so the client renders rows without parsing the whole
// setup/metrics documents: the SQL grade of the SERVER accuracy (run_grade —
// the fenced mirror of the core's gradeOf), the consistency and chars slices
// of server_metrics (absent until judged), and the run_quote_id / run_mods
// selections of the setup snapshot the leaderboard projection already uses,
// plus run_adopted_from — the seeded-repeat marker, which is what lets a row
// render "saved, not counted" without the client re-deriving eligibility.
//
// The verdict join is the ONLY join here — a primary-key probe per row on the
// 1:1 satellite. Still none to quotes or anything else: this is the profile
// page's hot query with pinned plans on a 100k-run account (docs/PERFORMANCE.md
// zone 9), and a quote's own text and length band are already served, cached by
// id, by GET /quotes/{id} — the same call the quote board's heading makes.
// One jsonb document rather than five columns so nullability stays a property
// of the data (jsonb_strip_nulls) instead of five hand-annotated scan types.
func (q *Queries) ListRunsFirst(ctx context.Context, arg ListRunsFirstParams) ([]ListRunsFirstRow, error) {
	rows, err := q.db.Query(ctx, listRunsFirst, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRunsFirstRow{}
	for rows.Next() {
		var i ListRunsFirstRow
		if err := rows.Scan(
			&i.ID,
			&i.Mode,
			&i.DurationMs,
			&i.WordCount,
			&i.Lang,
			&i.Seed,
			&i.DictHash,
			&i.Setup,
			&i.ClientMetrics,
			&i.ClientScore,
			&i.ScoreVersion,
			&i.Status,
			&i.ServerMetrics,
			&i.ServerScore,
			&i.Validation,
			&i.ValidatedAt,
			&i.LogBytes,
			&i.RestartsSinceLastSubmit,
			&i.CreatedAt,
			&i.Derived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsForReview = `-- name: ListRunsForReview :many
SELECT r.id, r.user_id, u.display_name, r.status, r.mode, r.lang, r.created_at,
       v.server_metrics, v.validation,
       (v.validation -> 'policy' ->> 'suspicion')::numeric AS suspicion,
       EXISTS (SELECT 1 FROM run_status_overrides o WHERE o.run_id = r.id) AS already_overridden,
       COUNT(*) OVER () AS total
FROM runs r
         JOIN run_verdicts v ON v.run_id = r.id
         LEFT JOIN users u ON u.id = r.user_id
WHERE r.status <> 'pending'
  AND COALESCE((v.validation -> 'policy' ->> 'suspicion')::numeric, 0) >= $1::numeric
ORDER BY
    CASE WHEN $2::text = 'player' THEN lower(u.display_name) END ASC NULLS LAST,
    CASE WHEN $2::text = 'suspicion'
        THEN (v.validation -> 'policy' ->> 'suspicion')::numeric END DESC NULLS LAST,
    r.created_at DESC
LIMIT $4 OFFSET $3
`

type ListRunsForReviewParams struct {
	MinSuspicion pgtype.Numeric
	SortKey      string
	RowOffset    int32
	RowLimit     int32
}

type ListRunsForReviewRow struct {
	ID                uuid.UUID
	UserID            uuid.UUID
	DisplayName       *string
	Status            string
	Mode              string
	Lang              string
	CreatedAt         time.Time
	ServerMetrics     []byte
	Validation        json.RawMessage
	Suspicion         pgtype.Numeric
	AlreadyOverridden bool
	Total             int64
}

// The review queue: judged runs the policy scored at or above a suspicion floor,
// worst first.
//
// It reads `accepted` runs too, and that is the whole point of it. A run that
// crossed the threshold is already `flagged` and easy to find; the runs worth a
// human's attention are the ones carrying real suspicion that did NOT cross it,
// which is precisely where `sustained_superhuman` now leaves a superhuman speed.
// A queue that only listed `flagged` would show the cases the machine was
// already sure about and hide the ones it wanted help with.
// Sorting is a CASE ladder keyed by @sort_key ('suspicion' | 'date' |
// 'player'): exactly one CASE is non-null per key, the rest sort as equal, and
// created_at breaks every tie. COUNT(*) OVER () carries the pre-LIMIT total on
// every row, which is what lets the client paginate without a second query.
func (q *Queries) ListRunsForReview(ctx context.Context, arg ListRunsForReviewParams) ([]ListRunsForReviewRow, error) {
	rows, err := q.db.Query(ctx, listRunsForReview,
		arg.MinSuspicion,
		arg.SortKey,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRunsForReviewRow{}
	for rows.Next() {
		var i ListRunsForReviewRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DisplayName,
			&i.Status,
			&i.Mode,
			&i.Lang,
			&i.CreatedAt,
			&i.ServerMetrics,
			&i.Validation,
			&i.Suspicion,
			&i.AlreadyOverridden,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const runStatusForOverride = `-- name: RunStatusForOverride :one
SELECT r.status,
       EXISTS (SELECT 1 FROM run_status_overrides o WHERE o.run_id = r.id) AS already_overridden
FROM runs r
WHERE r.id = $1
FOR UPDATE
`

type RunStatusForOverrideRow struct {
	Status            string
	AlreadyOverridden bool
}

// The run as an operator override needs it: its current status, and whether a
// human has already decided about it. Locked FOR UPDATE so two operators acting
// on the same run at the same time serialise instead of both reading the
// pre-move status and writing contradictory audit rows.
func (q *Queries) RunStatusForOverride(ctx context.Context, id uuid.UUID) (RunStatusForOverrideRow, error) {
	row := q.db.QueryRow(ctx, runStatusForOverride, id)
	var i RunStatusForOverrideRow
	err := row.Scan(&i.Status, &i.AlreadyOverridden)
	return i, err
}

const setRunStatus = `-- name: SetRunStatus :exec
UPDATE runs SET status = $2 WHERE id = $1
`

type SetRunStatusParams struct {
	ID     uuid.UUID
	Status string
}

// The status write itself. Deliberately narrow: it touches `status` and nothing
// else, because the verdict, the server's numbers and the client's stay exactly
// as the worker recorded them. An override disagrees with what the evidence was
// taken to MEAN; it does not rewrite the evidence.
func (q *Queries) SetRunStatus(ctx context.Context, arg SetRunStatusParams) error {
	_, err := q.db.Exec(ctx, setRunStatus, arg.ID, arg.Status)
	return err
}
