// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package runsdb

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createRun = `-- name: CreateRun :one

INSERT INTO runs (
    user_id, mode, duration_ms, word_count, lang, seed, dict_hash,
    setup, client_metrics, client_score, score_version, log, log_bytes,
    restarts_since_last_submit
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
RETURNING id, status, created_at
`

type CreateRunParams struct {
	UserID                  uuid.UUID
	Mode                    string
	DurationMs              *int32
	WordCount               *int32
	Lang                    string
	Seed                    int64
	DictHash                string
	Setup                   json.RawMessage
	ClientMetrics           json.RawMessage
	ClientScore             json.RawMessage
	ScoreVersion            int16
	Log                     []byte
	LogBytes                int32
	RestartsSinceLastSubmit int32
}

type CreateRunRow struct {
	ID        uuid.UUID
	Status    string
	CreatedAt time.Time
}

// Queries for the runs domain. sqlc generates type-safe Go from these into
// internal/runs/runsdb. The gzip log blob is written once at ingestion and read
// back only through GetRunLog (the ?log=1 detail flag) and GetPublicReplayLog
// (the public log route); the summary queries deliberately never SELECT it.
func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (CreateRunRow, error) {
	row := q.db.QueryRow(ctx, createRun,
		arg.UserID,
		arg.Mode,
		arg.DurationMs,
		arg.WordCount,
		arg.Lang,
		arg.Seed,
		arg.DictHash,
		arg.Setup,
		arg.ClientMetrics,
		arg.ClientScore,
		arg.ScoreVersion,
		arg.Log,
		arg.LogBytes,
		arg.RestartsSinceLastSubmit,
	)
	var i CreateRunRow
	err := row.Scan(&i.ID, &i.Status, &i.CreatedAt)
	return i, err
}

const getPublicReplay = `-- name: GetPublicReplay :one
SELECT r.setup, r.server_metrics, r.server_score,
       run_grade((r.server_metrics ->> 'accuracy')::numeric)::text AS grade,
       r.mode, r.duration_ms, r.word_count, r.lang, r.seed, r.dict_hash,
       r.created_at, u.display_name
FROM runs r
         JOIN users u ON u.id = r.user_id
WHERE r.id = $1
  AND r.status = 'accepted'
  AND jsonb_typeof(r.server_metrics -> 'accuracy') = 'number'
  AND NOT EXISTS (SELECT 1 FROM active_bans b WHERE b.user_id = r.user_id)
`

type GetPublicReplayRow struct {
	Setup         json.RawMessage
	ServerMetrics []byte
	ServerScore   []byte
	Grade         string
	Mode          string
	DurationMs    *int32
	WordCount     *int32
	Lang          string
	Seed          int64
	DictHash      string
	CreatedAt     time.Time
	DisplayName   string
}

// Everything needed to describe someone else's run: the setup and the seed to
// regenerate the text, the dict_hash to verify the dictionary that regeneration
// is fed, and the server's own verdict numbers. The log is NOT here — it is a
// separate route (GetPublicReplayLog) so the stored gzip blob can go straight
// to the socket instead of being gunzipped into a JSON envelope
// (docs/PERFORMANCE.md, zone 6).
//
// seed and dict_hash are the same two columns the owner's authenticated summary
// already exposes (docs/RUNS.md); the word list is regenerated on the client
// from them, so the server never ships a word list it would then have to keep
// in sync with the core's generator.
//
// Three access rules are in the WHERE clause rather than in Go, so no caller can
// reach this data without them: the run must be ACCEPTED (a flagged, rejected
// or unjudged run is not a public artefact), and its owner must not be banned.
// All three failures return no row, which the handler renders as one
// indistinguishable 404 — a leaderboard must not leak who is under review.
func (q *Queries) GetPublicReplay(ctx context.Context, runID uuid.UUID) (GetPublicReplayRow, error) {
	row := q.db.QueryRow(ctx, getPublicReplay, runID)
	var i GetPublicReplayRow
	err := row.Scan(
		&i.Setup,
		&i.ServerMetrics,
		&i.ServerScore,
		&i.Grade,
		&i.Mode,
		&i.DurationMs,
		&i.WordCount,
		&i.Lang,
		&i.Seed,
		&i.DictHash,
		&i.CreatedAt,
		&i.DisplayName,
	)
	return i, err
}

const getPublicReplayLog = `-- name: GetPublicReplayLog :one
SELECT r.log
FROM runs r
         JOIN users u ON u.id = r.user_id
WHERE r.id = $1
  AND r.status = 'accepted'
  AND jsonb_typeof(r.server_metrics -> 'accuracy') = 'number'
  AND NOT EXISTS (SELECT 1 FROM active_bans b WHERE b.user_id = r.user_id)
`

// The stored gzip event log of one publicly watchable run, and nothing else, so
// the log route never re-reads the metadata it is not going to serve.
//
// The WHERE clause is the SAME THREE RULES, spelled the same way, including the
// join to users: eligibility for the log must be eligibility for the metadata,
// character for character, or the two routes drift into two access matrices.
func (q *Queries) GetPublicReplayLog(ctx context.Context, runID uuid.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getPublicReplayLog, runID)
	var log []byte
	err := row.Scan(&log)
	return log, err
}

const getRun = `-- name: GetRun :one
SELECT id, mode, duration_ms, word_count, lang, seed, dict_hash,
       setup, client_metrics, client_score, score_version, status,
       server_metrics, server_score, validation, validated_at,
       log_bytes, restarts_since_last_submit, created_at
FROM runs
WHERE id = $1 AND user_id = $2
`

type GetRunParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

type GetRunRow struct {
	ID                      uuid.UUID
	Mode                    string
	DurationMs              *int32
	WordCount               *int32
	Lang                    string
	Seed                    int64
	DictHash                string
	Setup                   json.RawMessage
	ClientMetrics           json.RawMessage
	ClientScore             json.RawMessage
	ScoreVersion            int16
	Status                  string
	ServerMetrics           []byte
	ServerScore             []byte
	Validation              []byte
	ValidatedAt             *time.Time
	LogBytes                int32
	RestartsSinceLastSubmit int32
	CreatedAt               time.Time
}

// One run's summary (no log payload), scoped to its owner.
func (q *Queries) GetRun(ctx context.Context, arg GetRunParams) (GetRunRow, error) {
	row := q.db.QueryRow(ctx, getRun, arg.ID, arg.UserID)
	var i GetRunRow
	err := row.Scan(
		&i.ID,
		&i.Mode,
		&i.DurationMs,
		&i.WordCount,
		&i.Lang,
		&i.Seed,
		&i.DictHash,
		&i.Setup,
		&i.ClientMetrics,
		&i.ClientScore,
		&i.ScoreVersion,
		&i.Status,
		&i.ServerMetrics,
		&i.ServerScore,
		&i.Validation,
		&i.ValidatedAt,
		&i.LogBytes,
		&i.RestartsSinceLastSubmit,
		&i.CreatedAt,
	)
	return i, err
}

const getRunLog = `-- name: GetRunLog :one
SELECT log FROM runs
WHERE id = $1 AND user_id = $2
`

type GetRunLogParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// The gzip log blob for one run, scoped to its owner (the ?log=1 detail flag).
func (q *Queries) GetRunLog(ctx context.Context, arg GetRunLogParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getRunLog, arg.ID, arg.UserID)
	var log []byte
	err := row.Scan(&log)
	return log, err
}

const listRunsAfter = `-- name: ListRunsAfter :many
SELECT id, mode, duration_ms, word_count, lang, seed, dict_hash,
       setup, client_metrics, client_score, score_version, status,
       server_metrics, server_score, validation, validated_at,
       log_bytes, restarts_since_last_submit, created_at
FROM runs
WHERE user_id = $1
  AND (created_at < $2 OR (created_at = $2 AND id < $3))
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListRunsAfterParams struct {
	UserID    uuid.UUID
	CreatedAt time.Time
	ID        uuid.UUID
	Limit     int32
}

type ListRunsAfterRow struct {
	ID                      uuid.UUID
	Mode                    string
	DurationMs              *int32
	WordCount               *int32
	Lang                    string
	Seed                    int64
	DictHash                string
	Setup                   json.RawMessage
	ClientMetrics           json.RawMessage
	ClientScore             json.RawMessage
	ScoreVersion            int16
	Status                  string
	ServerMetrics           []byte
	ServerScore             []byte
	Validation              []byte
	ValidatedAt             *time.Time
	LogBytes                int32
	RestartsSinceLastSubmit int32
	CreatedAt               time.Time
}

// Next page after the (created_at, id) cursor. The row-value comparison written
// out longhand keeps sqlc's type inference happy and matches the composite
// (created_at DESC, id DESC) ordering exactly.
func (q *Queries) ListRunsAfter(ctx context.Context, arg ListRunsAfterParams) ([]ListRunsAfterRow, error) {
	rows, err := q.db.Query(ctx, listRunsAfter,
		arg.UserID,
		arg.CreatedAt,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRunsAfterRow{}
	for rows.Next() {
		var i ListRunsAfterRow
		if err := rows.Scan(
			&i.ID,
			&i.Mode,
			&i.DurationMs,
			&i.WordCount,
			&i.Lang,
			&i.Seed,
			&i.DictHash,
			&i.Setup,
			&i.ClientMetrics,
			&i.ClientScore,
			&i.ScoreVersion,
			&i.Status,
			&i.ServerMetrics,
			&i.ServerScore,
			&i.Validation,
			&i.ValidatedAt,
			&i.LogBytes,
			&i.RestartsSinceLastSubmit,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsFirst = `-- name: ListRunsFirst :many
SELECT id, mode, duration_ms, word_count, lang, seed, dict_hash,
       setup, client_metrics, client_score, score_version, status,
       server_metrics, server_score, validation, validated_at,
       log_bytes, restarts_since_last_submit, created_at
FROM runs
WHERE user_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListRunsFirstParams struct {
	UserID uuid.UUID
	Limit  int32
}

type ListRunsFirstRow struct {
	ID                      uuid.UUID
	Mode                    string
	DurationMs              *int32
	WordCount               *int32
	Lang                    string
	Seed                    int64
	DictHash                string
	Setup                   json.RawMessage
	ClientMetrics           json.RawMessage
	ClientScore             json.RawMessage
	ScoreVersion            int16
	Status                  string
	ServerMetrics           []byte
	ServerScore             []byte
	Validation              []byte
	ValidatedAt             *time.Time
	LogBytes                int32
	RestartsSinceLastSubmit int32
	CreatedAt               time.Time
}

// First page of a user's runs, newest first. Keyset pagination continues via
// ListRunsAfter using the (created_at, id) of the last row. The replay columns
// (server_metrics/server_score/validation/validated_at) are NULL until the
// worker has judged the run.
func (q *Queries) ListRunsFirst(ctx context.Context, arg ListRunsFirstParams) ([]ListRunsFirstRow, error) {
	rows, err := q.db.Query(ctx, listRunsFirst, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRunsFirstRow{}
	for rows.Next() {
		var i ListRunsFirstRow
		if err := rows.Scan(
			&i.ID,
			&i.Mode,
			&i.DurationMs,
			&i.WordCount,
			&i.Lang,
			&i.Seed,
			&i.DictHash,
			&i.Setup,
			&i.ClientMetrics,
			&i.ClientScore,
			&i.ScoreVersion,
			&i.Status,
			&i.ServerMetrics,
			&i.ServerScore,
			&i.Validation,
			&i.ValidatedAt,
			&i.LogBytes,
			&i.RestartsSinceLastSubmit,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
