// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package runsdb

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createRun = `-- name: CreateRun :one

INSERT INTO runs (
    user_id, mode, duration_ms, word_count, lang, seed, dict_hash,
    setup, client_metrics, client_score, score_version, log, log_bytes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
RETURNING id, status, created_at
`

type CreateRunParams struct {
	UserID        uuid.UUID
	Mode          string
	DurationMs    *int32
	WordCount     *int32
	Lang          string
	Seed          int64
	DictHash      string
	Setup         json.RawMessage
	ClientMetrics json.RawMessage
	ClientScore   json.RawMessage
	ScoreVersion  int16
	Log           []byte
	LogBytes      int32
}

type CreateRunRow struct {
	ID        uuid.UUID
	Status    string
	CreatedAt time.Time
}

// Queries for the runs domain. sqlc generates type-safe Go from these into
// internal/runs/runsdb. The gzip log blob is written once at ingestion and read
// back only through GetRunLog (the ?log=1 detail flag); the summary queries
// deliberately never SELECT it.
func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (CreateRunRow, error) {
	row := q.db.QueryRow(ctx, createRun,
		arg.UserID,
		arg.Mode,
		arg.DurationMs,
		arg.WordCount,
		arg.Lang,
		arg.Seed,
		arg.DictHash,
		arg.Setup,
		arg.ClientMetrics,
		arg.ClientScore,
		arg.ScoreVersion,
		arg.Log,
		arg.LogBytes,
	)
	var i CreateRunRow
	err := row.Scan(&i.ID, &i.Status, &i.CreatedAt)
	return i, err
}

const getRun = `-- name: GetRun :one
SELECT id, mode, duration_ms, word_count, lang, seed, dict_hash,
       setup, client_metrics, client_score, score_version, status,
       log_bytes, created_at
FROM runs
WHERE id = $1 AND user_id = $2
`

type GetRunParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

type GetRunRow struct {
	ID            uuid.UUID
	Mode          string
	DurationMs    *int32
	WordCount     *int32
	Lang          string
	Seed          int64
	DictHash      string
	Setup         json.RawMessage
	ClientMetrics json.RawMessage
	ClientScore   json.RawMessage
	ScoreVersion  int16
	Status        string
	LogBytes      int32
	CreatedAt     time.Time
}

// One run's summary (no log payload), scoped to its owner.
func (q *Queries) GetRun(ctx context.Context, arg GetRunParams) (GetRunRow, error) {
	row := q.db.QueryRow(ctx, getRun, arg.ID, arg.UserID)
	var i GetRunRow
	err := row.Scan(
		&i.ID,
		&i.Mode,
		&i.DurationMs,
		&i.WordCount,
		&i.Lang,
		&i.Seed,
		&i.DictHash,
		&i.Setup,
		&i.ClientMetrics,
		&i.ClientScore,
		&i.ScoreVersion,
		&i.Status,
		&i.LogBytes,
		&i.CreatedAt,
	)
	return i, err
}

const getRunLog = `-- name: GetRunLog :one
SELECT log FROM runs
WHERE id = $1 AND user_id = $2
`

type GetRunLogParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// The gzip log blob for one run, scoped to its owner (the ?log=1 detail flag).
func (q *Queries) GetRunLog(ctx context.Context, arg GetRunLogParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getRunLog, arg.ID, arg.UserID)
	var log []byte
	err := row.Scan(&log)
	return log, err
}

const listRunsAfter = `-- name: ListRunsAfter :many
SELECT id, mode, duration_ms, word_count, lang, seed, dict_hash,
       setup, client_metrics, client_score, score_version, status,
       log_bytes, created_at
FROM runs
WHERE user_id = $1
  AND (created_at < $2 OR (created_at = $2 AND id < $3))
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListRunsAfterParams struct {
	UserID    uuid.UUID
	CreatedAt time.Time
	ID        uuid.UUID
	Limit     int32
}

type ListRunsAfterRow struct {
	ID            uuid.UUID
	Mode          string
	DurationMs    *int32
	WordCount     *int32
	Lang          string
	Seed          int64
	DictHash      string
	Setup         json.RawMessage
	ClientMetrics json.RawMessage
	ClientScore   json.RawMessage
	ScoreVersion  int16
	Status        string
	LogBytes      int32
	CreatedAt     time.Time
}

// Next page after the (created_at, id) cursor. The row-value comparison written
// out longhand keeps sqlc's type inference happy and matches the composite
// (created_at DESC, id DESC) ordering exactly.
func (q *Queries) ListRunsAfter(ctx context.Context, arg ListRunsAfterParams) ([]ListRunsAfterRow, error) {
	rows, err := q.db.Query(ctx, listRunsAfter,
		arg.UserID,
		arg.CreatedAt,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRunsAfterRow{}
	for rows.Next() {
		var i ListRunsAfterRow
		if err := rows.Scan(
			&i.ID,
			&i.Mode,
			&i.DurationMs,
			&i.WordCount,
			&i.Lang,
			&i.Seed,
			&i.DictHash,
			&i.Setup,
			&i.ClientMetrics,
			&i.ClientScore,
			&i.ScoreVersion,
			&i.Status,
			&i.LogBytes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsFirst = `-- name: ListRunsFirst :many
SELECT id, mode, duration_ms, word_count, lang, seed, dict_hash,
       setup, client_metrics, client_score, score_version, status,
       log_bytes, created_at
FROM runs
WHERE user_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListRunsFirstParams struct {
	UserID uuid.UUID
	Limit  int32
}

type ListRunsFirstRow struct {
	ID            uuid.UUID
	Mode          string
	DurationMs    *int32
	WordCount     *int32
	Lang          string
	Seed          int64
	DictHash      string
	Setup         json.RawMessage
	ClientMetrics json.RawMessage
	ClientScore   json.RawMessage
	ScoreVersion  int16
	Status        string
	LogBytes      int32
	CreatedAt     time.Time
}

// First page of a user's runs, newest first. Keyset pagination continues via
// ListRunsAfter using the (created_at, id) of the last row.
func (q *Queries) ListRunsFirst(ctx context.Context, arg ListRunsFirstParams) ([]ListRunsFirstRow, error) {
	rows, err := q.db.Query(ctx, listRunsFirst, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRunsFirstRow{}
	for rows.Next() {
		var i ListRunsFirstRow
		if err := rows.Scan(
			&i.ID,
			&i.Mode,
			&i.DurationMs,
			&i.WordCount,
			&i.Lang,
			&i.Seed,
			&i.DictHash,
			&i.Setup,
			&i.ClientMetrics,
			&i.ClientScore,
			&i.ScoreVersion,
			&i.Status,
			&i.LogBytes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
