// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package moderationdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const activeBanFor = `-- name: ActiveBanFor :one
SELECT b.id, b.user_id, b.reason, b.issued_by, b.issued_at, b.expires_at, b.revoked_at
FROM bans b
WHERE b.user_id = $1
  AND EXISTS (SELECT 1 FROM active_bans a WHERE a.user_id = b.user_id)
  AND b.revoked_at IS NULL
  AND (b.expires_at IS NULL OR b.expires_at > now())
ORDER BY b.issued_at DESC
LIMIT 1
`

type ActiveBanForRow struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Reason    string
	IssuedBy  *string
	IssuedAt  time.Time
	ExpiresAt *time.Time
	RevokedAt *time.Time
}

// The one ban currently in force for a user, if any.
func (q *Queries) ActiveBanFor(ctx context.Context, userID uuid.UUID) (ActiveBanForRow, error) {
	row := q.db.QueryRow(ctx, activeBanFor, userID)
	var i ActiveBanForRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Reason,
		&i.IssuedBy,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const insertBan = `-- name: InsertBan :one
INSERT INTO bans (user_id, reason, issued_by, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, reason, issued_by, issued_at, expires_at, revoked_at
`

type InsertBanParams struct {
	UserID    uuid.UUID
	Reason    string
	IssuedBy  *string
	ExpiresAt *time.Time
}

type InsertBanRow struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Reason    string
	IssuedBy  *string
	IssuedAt  time.Time
	ExpiresAt *time.Time
	RevokedAt *time.Time
}

func (q *Queries) InsertBan(ctx context.Context, arg InsertBanParams) (InsertBanRow, error) {
	row := q.db.QueryRow(ctx, insertBan,
		arg.UserID,
		arg.Reason,
		arg.IssuedBy,
		arg.ExpiresAt,
	)
	var i InsertBanRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Reason,
		&i.IssuedBy,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const isRestricted = `-- name: IsRestricted :one
SELECT EXISTS (SELECT 1 FROM active_bans a WHERE a.user_id = $1)
`

// The whole of what the rest of the server asks about a ban: yes or no, right
// now. No reason, no expiry — the player-facing banner is deliberately opaque
// and there is nothing here for a handler to leak.
func (q *Queries) IsRestricted(ctx context.Context, userID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isRestricted, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listBans = `-- name: ListBans :many
SELECT b.id, b.user_id, u.display_name, b.reason, b.issued_by, b.issued_at,
       b.expires_at, b.revoked_at,
       EXISTS (SELECT 1
               FROM active_bans a
               WHERE a.user_id = b.user_id) AS user_restricted
FROM bans b
         JOIN users u ON u.id = b.user_id
WHERE NOT $1::boolean
   OR (b.revoked_at IS NULL AND (b.expires_at IS NULL OR b.expires_at > now()))
ORDER BY b.issued_at DESC
LIMIT $2
`

type ListBansParams struct {
	OnlyActive bool
	RowLimit   int32
}

type ListBansRow struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	DisplayName    string
	Reason         string
	IssuedBy       *string
	IssuedAt       time.Time
	ExpiresAt      *time.Time
	RevokedAt      *time.Time
	UserRestricted bool
}

// Every ban, newest first, with the display name and whether it is in force.
// `only_active` filters through the view rather than re-deriving the predicate.
func (q *Queries) ListBans(ctx context.Context, arg ListBansParams) ([]ListBansRow, error) {
	rows, err := q.db.Query(ctx, listBans, arg.OnlyActive, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBansRow{}
	for rows.Next() {
		var i ListBansRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DisplayName,
			&i.Reason,
			&i.IssuedBy,
			&i.IssuedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.UserRestricted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBansForUser = `-- name: ListBansForUser :many
SELECT b.id, b.user_id, u.display_name, b.reason, b.issued_by, b.issued_at,
       b.expires_at, b.revoked_at,
       EXISTS (SELECT 1
               FROM active_bans a
               WHERE a.user_id = b.user_id) AS user_restricted
FROM bans b
         JOIN users u ON u.id = b.user_id
WHERE b.user_id = $1
ORDER BY b.issued_at DESC
`

type ListBansForUserRow struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	DisplayName    string
	Reason         string
	IssuedBy       *string
	IssuedAt       time.Time
	ExpiresAt      *time.Time
	RevokedAt      *time.Time
	UserRestricted bool
}

func (q *Queries) ListBansForUser(ctx context.Context, userID uuid.UUID) ([]ListBansForUserRow, error) {
	rows, err := q.db.Query(ctx, listBansForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBansForUserRow{}
	for rows.Next() {
		var i ListBansForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DisplayName,
			&i.Reason,
			&i.IssuedBy,
			&i.IssuedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.UserRestricted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveUserByDisplayName = `-- name: ResolveUserByDisplayName :many
SELECT u.id, u.display_name
FROM users u
WHERE u.display_name = $1
ORDER BY u.id
LIMIT 10
`

type ResolveUserByDisplayNameRow struct {
	ID          uuid.UUID
	DisplayName string
}

// Many, not one: display names are not unique, and a moderator who typed an
// ambiguous one must be told rather than have the tool pick.
func (q *Queries) ResolveUserByDisplayName(ctx context.Context, displayName string) ([]ResolveUserByDisplayNameRow, error) {
	rows, err := q.db.Query(ctx, resolveUserByDisplayName, displayName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResolveUserByDisplayNameRow{}
	for rows.Next() {
		var i ResolveUserByDisplayNameRow
		if err := rows.Scan(&i.ID, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveUserByEmail = `-- name: ResolveUserByEmail :many
SELECT DISTINCT u.id, u.display_name
FROM users u
         JOIN auth_identities ai ON ai.user_id = u.id
WHERE lower(ai.email) = lower($1)
ORDER BY u.id
LIMIT 10
`

type ResolveUserByEmailRow struct {
	ID          uuid.UUID
	DisplayName string
}

// An account may hold several identities; the email is the one a moderator has
// in hand from a report.
func (q *Queries) ResolveUserByEmail(ctx context.Context, email string) ([]ResolveUserByEmailRow, error) {
	rows, err := q.db.Query(ctx, resolveUserByEmail, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResolveUserByEmailRow{}
	for rows.Next() {
		var i ResolveUserByEmailRow
		if err := rows.Scan(&i.ID, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveUserByID = `-- name: ResolveUserByID :one

SELECT u.id, u.display_name
FROM users u
WHERE u.id = $1
`

type ResolveUserByIDRow struct {
	ID          uuid.UUID
	DisplayName string
}

// Moderation: issuing, revoking and reading bans.
//
// "Banned right now" is defined ONCE, in the active_bans view
// (db/migrations/00012). Nothing in this file repeats
// `revoked_at IS NULL AND (expires_at IS NULL OR expires_at > now())`; every
// query that needs it joins the view. That is what makes a temporary ban lift
// itself and an unban restore a player instantly, everywhere, with no rebuild
// and no janitor — there is one predicate and every reader is behind it.
func (q *Queries) ResolveUserByID(ctx context.Context, id uuid.UUID) (ResolveUserByIDRow, error) {
	row := q.db.QueryRow(ctx, resolveUserByID, id)
	var i ResolveUserByIDRow
	err := row.Scan(&i.ID, &i.DisplayName)
	return i, err
}

const revokeBan = `-- name: RevokeBan :one
UPDATE bans
SET revoked_at = now()
WHERE id = $1 AND revoked_at IS NULL
RETURNING id, user_id, reason, issued_by, issued_at, expires_at, revoked_at
`

type RevokeBanRow struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Reason    string
	IssuedBy  *string
	IssuedAt  time.Time
	ExpiresAt *time.Time
	RevokedAt *time.Time
}

func (q *Queries) RevokeBan(ctx context.Context, id uuid.UUID) (RevokeBanRow, error) {
	row := q.db.QueryRow(ctx, revokeBan, id)
	var i RevokeBanRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Reason,
		&i.IssuedBy,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const updateBan = `-- name: UpdateBan :one
UPDATE bans
SET reason     = $1,
    issued_by  = $2,
    expires_at = $3,
    issued_at  = now()
WHERE id = $4
RETURNING id, user_id, reason, issued_by, issued_at, expires_at, revoked_at
`

type UpdateBanParams struct {
	Reason    string
	IssuedBy  *string
	ExpiresAt *time.Time
	ID        uuid.UUID
}

type UpdateBanRow struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Reason    string
	IssuedBy  *string
	IssuedAt  time.Time
	ExpiresAt *time.Time
	RevokedAt *time.Time
}

// Re-banning an already-banned user amends the ban in place rather than
// stacking a second one: two simultaneous bans on one account would make
// "when does this lift" a question with two answers.
func (q *Queries) UpdateBan(ctx context.Context, arg UpdateBanParams) (UpdateBanRow, error) {
	row := q.db.QueryRow(ctx, updateBan,
		arg.Reason,
		arg.IssuedBy,
		arg.ExpiresAt,
		arg.ID,
	)
	var i UpdateBanRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Reason,
		&i.IssuedBy,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}
