// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package authdb

import (
	"time"

	"github.com/google/uuid"
)

type AuthIdentity struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	Provider        string
	ProviderSubject string
	Email           *string
	EmailVerified   bool
	CreatedAt       time.Time
}

type EmailToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Purpose   string
	TokenHash []byte
	ExpiresAt time.Time
	UsedAt    *time.Time
	CreatedAt time.Time
}

type Session struct {
	ID         uuid.UUID
	TokenHash  []byte
	UserID     uuid.UUID
	CreatedAt  time.Time
	ExpiresAt  time.Time
	LastSeenAt time.Time
}

type User struct {
	ID          uuid.UUID
	DisplayName string
	CreatedAt   time.Time
}

type UserCredential struct {
	UserID       uuid.UUID
	Argon2idHash string
	UpdatedAt    time.Time
}
