// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package authdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const changeDisplayName = `-- name: ChangeDisplayName :one
UPDATE users
SET display_name = $2, display_name_changed_at = now(), updated_at = now()
WHERE id = $1
  AND (display_name_changed_at IS NULL
       OR display_name_changed_at <= now() - interval '30 days')
RETURNING id, display_name, created_at, profile_public, keyboard_public, updated_at, role, bio, keyboard, display_name_changed_at
`

type ChangeDisplayNameParams struct {
	ID          uuid.UUID
	DisplayName string
}

// The rename, with the once-per-30-days rule INSIDE the predicate: zero rows
// for an authenticated caller means the cooldown refused the write (the
// adapter reports that as ErrDisplayNameCooldown), so check and write cannot
// race. The interval is fixed here and mirrored by displayNameCooldown in
// handler.go — change both together.
func (q *Queries) ChangeDisplayName(ctx context.Context, arg ChangeDisplayNameParams) (User, error) {
	row := q.db.QueryRow(ctx, changeDisplayName, arg.ID, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.CreatedAt,
		&i.ProfilePublic,
		&i.KeyboardPublic,
		&i.UpdatedAt,
		&i.Role,
		&i.Bio,
		&i.Keyboard,
		&i.DisplayNameChangedAt,
	)
	return i, err
}

const createEmailToken = `-- name: CreateEmailToken :one
INSERT INTO email_tokens (user_id, purpose, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, purpose, token_hash, expires_at, used_at, created_at
`

type CreateEmailTokenParams struct {
	UserID    uuid.UUID
	Purpose   string
	TokenHash []byte
	ExpiresAt time.Time
}

func (q *Queries) CreateEmailToken(ctx context.Context, arg CreateEmailTokenParams) (EmailToken, error) {
	row := q.db.QueryRow(ctx, createEmailToken,
		arg.UserID,
		arg.Purpose,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i EmailToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Purpose,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createIdentity = `-- name: CreateIdentity :one
INSERT INTO auth_identities (user_id, provider, provider_subject, email, email_verified)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, provider, provider_subject, email, email_verified, created_at
`

type CreateIdentityParams struct {
	UserID          uuid.UUID
	Provider        string
	ProviderSubject string
	Email           *string
	EmailVerified   bool
}

func (q *Queries) CreateIdentity(ctx context.Context, arg CreateIdentityParams) (AuthIdentity, error) {
	row := q.db.QueryRow(ctx, createIdentity,
		arg.UserID,
		arg.Provider,
		arg.ProviderSubject,
		arg.Email,
		arg.EmailVerified,
	)
	var i AuthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderSubject,
		&i.Email,
		&i.EmailVerified,
		&i.CreatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (token_hash, user_id, expires_at)
VALUES ($1, $2, $3)
RETURNING id, token_hash, user_id, created_at, expires_at, last_seen_at
`

type CreateSessionParams struct {
	TokenHash []byte
	UserID    uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastSeenAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (display_name)
VALUES ($1)
RETURNING id, display_name, created_at, profile_public, keyboard_public, updated_at, role, bio, keyboard, display_name_changed_at
`

// Queries for the auth domain. sqlc generates type-safe Go from these into
// internal/auth/authdb. Transactions that span several of them (register, oauth
// create) are composed in the Postgres store adapter, not here.
func (q *Queries) CreateUser(ctx context.Context, displayName string) (User, error) {
	row := q.db.QueryRow(ctx, createUser, displayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.CreatedAt,
		&i.ProfilePublic,
		&i.KeyboardPublic,
		&i.UpdatedAt,
		&i.Role,
		&i.Bio,
		&i.Keyboard,
		&i.DisplayNameChangedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSessionByTokenHash = `-- name: DeleteSessionByTokenHash :exec
DELETE FROM sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSessionByTokenHash(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSessionByTokenHash, tokenHash)
	return err
}

const deleteStaleEmailTokens = `-- name: DeleteStaleEmailTokens :execrows
DELETE FROM email_tokens
WHERE expires_at < now() - interval '24 hours'
   OR used_at   < now() - interval '24 hours'
`

// Janitor sweep: tokens that expired, or were consumed, more than 24 hours ago.
// Recently expired/used rows are kept briefly for debugging; UseEmailToken
// already refuses them regardless.
func (q *Queries) DeleteStaleEmailTokens(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStaleEmailTokens)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM sessions WHERE user_id = $1
`

func (q *Queries) DeleteUserSessions(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserSessions, userID)
	return err
}

const deleteUserTokensByPurpose = `-- name: DeleteUserTokensByPurpose :exec
DELETE FROM email_tokens WHERE user_id = $1 AND purpose = $2
`

type DeleteUserTokensByPurposeParams struct {
	UserID  uuid.UUID
	Purpose string
}

func (q *Queries) DeleteUserTokensByPurpose(ctx context.Context, arg DeleteUserTokensByPurposeParams) error {
	_, err := q.db.Exec(ctx, deleteUserTokensByPurpose, arg.UserID, arg.Purpose)
	return err
}

const getCredentialByUser = `-- name: GetCredentialByUser :one
SELECT user_id, argon2id_hash, updated_at FROM user_credentials WHERE user_id = $1
`

func (q *Queries) GetCredentialByUser(ctx context.Context, userID uuid.UUID) (UserCredential, error) {
	row := q.db.QueryRow(ctx, getCredentialByUser, userID)
	var i UserCredential
	err := row.Scan(&i.UserID, &i.Argon2idHash, &i.UpdatedAt)
	return i, err
}

const getEmailIdentityByEmail = `-- name: GetEmailIdentityByEmail :one
SELECT id, user_id, provider, provider_subject, email, email_verified, created_at FROM auth_identities
WHERE provider = 'email' AND email = $1
`

func (q *Queries) GetEmailIdentityByEmail(ctx context.Context, email *string) (AuthIdentity, error) {
	row := q.db.QueryRow(ctx, getEmailIdentityByEmail, email)
	var i AuthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderSubject,
		&i.Email,
		&i.EmailVerified,
		&i.CreatedAt,
	)
	return i, err
}

const getIdentityByProviderSubject = `-- name: GetIdentityByProviderSubject :one
SELECT id, user_id, provider, provider_subject, email, email_verified, created_at FROM auth_identities
WHERE provider = $1 AND provider_subject = $2
`

type GetIdentityByProviderSubjectParams struct {
	Provider        string
	ProviderSubject string
}

func (q *Queries) GetIdentityByProviderSubject(ctx context.Context, arg GetIdentityByProviderSubjectParams) (AuthIdentity, error) {
	row := q.db.QueryRow(ctx, getIdentityByProviderSubject, arg.Provider, arg.ProviderSubject)
	var i AuthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderSubject,
		&i.Email,
		&i.EmailVerified,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT id, token_hash, user_id, created_at, expires_at, last_seen_at FROM sessions WHERE token_hash = $1
`

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash []byte) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, display_name, created_at, profile_public, keyboard_public, updated_at, role, bio, keyboard, display_name_changed_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.CreatedAt,
		&i.ProfilePublic,
		&i.KeyboardPublic,
		&i.UpdatedAt,
		&i.Role,
		&i.Bio,
		&i.Keyboard,
		&i.DisplayNameChangedAt,
	)
	return i, err
}

const getVerifiedIdentityByEmail = `-- name: GetVerifiedIdentityByEmail :one
SELECT id, user_id, provider, provider_subject, email, email_verified, created_at FROM auth_identities
WHERE email = $1 AND email_verified
LIMIT 1
`

// Collision check for the no-auto-link policy: any VERIFIED identity (from any
// provider) already owning this email.
func (q *Queries) GetVerifiedIdentityByEmail(ctx context.Context, email *string) (AuthIdentity, error) {
	row := q.db.QueryRow(ctx, getVerifiedIdentityByEmail, email)
	var i AuthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderSubject,
		&i.Email,
		&i.EmailVerified,
		&i.CreatedAt,
	)
	return i, err
}

const listIdentitiesByUser = `-- name: ListIdentitiesByUser :many
SELECT id, user_id, provider, provider_subject, email, email_verified, created_at FROM auth_identities
WHERE user_id = $1
ORDER BY created_at
`

func (q *Queries) ListIdentitiesByUser(ctx context.Context, userID uuid.UUID) ([]AuthIdentity, error) {
	rows, err := q.db.Query(ctx, listIdentitiesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthIdentity{}
	for rows.Next() {
		var i AuthIdentity
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.ProviderSubject,
			&i.Email,
			&i.EmailVerified,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promoteAdmins = `-- name: PromoteAdmins :execrows
UPDATE users
SET role = 'admin', updated_at = now()
WHERE role <> 'admin'
  AND id IN (SELECT user_id
             FROM auth_identities
             WHERE email_verified
               AND email = ANY ($1::citext[]))
`

// The admin bootstrap (00023, docs/MODERATION.md): accounts owning a VERIFIED
// identity on one of the configured emails are promoted at startup. Verified
// only — an address someone merely typed must not confer a role. Promotion
// only, never demotion: the env list is how the first admin appears, not a
// sync source. Idempotent by the role guard, and the guard is also what keeps
// updated_at honest — an already-admin row is not touched.
func (q *Queries) PromoteAdmins(ctx context.Context, emails []string) (int64, error) {
	result, err := q.db.Exec(ctx, promoteAdmins, emails)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setIdentityEmailVerified = `-- name: SetIdentityEmailVerified :exec
UPDATE auth_identities SET email_verified = true WHERE id = $1
`

func (q *Queries) SetIdentityEmailVerified(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setIdentityEmailVerified, id)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_seen_at = now(), expires_at = $2 WHERE id = $1
`

type TouchSessionParams struct {
	ID        uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.Exec(ctx, touchSession, arg.ID, arg.ExpiresAt)
	return err
}

const updateUserSettings = `-- name: UpdateUserSettings :one
UPDATE users
SET profile_public = $2, keyboard_public = $3, updated_at = now()
WHERE id = $1
RETURNING id, display_name, created_at, profile_public, keyboard_public, updated_at, role, bio, keyboard, display_name_changed_at
`

type UpdateUserSettingsParams struct {
	ID             uuid.UUID
	ProfilePublic  bool
	KeyboardPublic bool
}

// The two privacy switches, replaced as a pair. The handler resolves a partial
// PATCH against the current row before calling this, so the statement itself
// stays a plain write with no COALESCE cleverness to test.
//
// updated_at is maintained HERE, by the writer, not by a trigger (00022): any
// future statement that mutates users must set it the same way.
func (q *Queries) UpdateUserSettings(ctx context.Context, arg UpdateUserSettingsParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserSettings, arg.ID, arg.ProfilePublic, arg.KeyboardPublic)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.CreatedAt,
		&i.ProfilePublic,
		&i.KeyboardPublic,
		&i.UpdatedAt,
		&i.Role,
		&i.Bio,
		&i.Keyboard,
		&i.DisplayNameChangedAt,
	)
	return i, err
}

const upsertCredential = `-- name: UpsertCredential :exec
INSERT INTO user_credentials (user_id, argon2id_hash)
VALUES ($1, $2)
ON CONFLICT (user_id)
DO UPDATE SET argon2id_hash = EXCLUDED.argon2id_hash, updated_at = now()
`

type UpsertCredentialParams struct {
	UserID       uuid.UUID
	Argon2idHash string
}

func (q *Queries) UpsertCredential(ctx context.Context, arg UpsertCredentialParams) error {
	_, err := q.db.Exec(ctx, upsertCredential, arg.UserID, arg.Argon2idHash)
	return err
}

const useEmailToken = `-- name: UseEmailToken :one
UPDATE email_tokens
SET used_at = now()
WHERE token_hash = $1
  AND purpose = $2
  AND used_at IS NULL
  AND expires_at > now()
RETURNING id, user_id, purpose, token_hash, expires_at, used_at, created_at
`

type UseEmailTokenParams struct {
	TokenHash []byte
	Purpose   string
}

// Atomically consume a token: marks it used only if unused, unexpired, and of
// the right purpose. A returned row means the token was valid and is now spent.
func (q *Queries) UseEmailToken(ctx context.Context, arg UseEmailTokenParams) (EmailToken, error) {
	row := q.db.QueryRow(ctx, useEmailToken, arg.TokenHash, arg.Purpose)
	var i EmailToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Purpose,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const verifyEmailIdentityByUser = `-- name: VerifyEmailIdentityByUser :exec
UPDATE auth_identities SET email_verified = true WHERE user_id = $1 AND provider = 'email'
`

func (q *Queries) VerifyEmailIdentityByUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, verifyEmailIdentityByUser, userID)
	return err
}
