// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package leaderboarddb

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const clearLeaderboard = `-- name: ClearLeaderboard :exec
TRUNCATE leaderboard_entries
`

// Rebuild step one. TRUNCATE is transactional in Postgres, so a failed rebuild
// leaves the old board untouched rather than an empty one.
func (q *Queries) ClearLeaderboard(ctx context.Context) error {
	_, err := q.db.Exec(ctx, clearLeaderboard)
	return err
}

const countLeaderboardAbove = `-- name: CountLeaderboardAbove :one
SELECT count(*)::bigint
FROM leaderboard_rows
WHERE bucket_key = $1
  AND (score > $2
       OR (score = $2 AND achieved_at < $3)
       OR (score = $2 AND achieved_at = $3 AND user_id < $4))
`

type CountLeaderboardAboveParams struct {
	BucketKey  string
	Score      int64
	AchievedAt time.Time
	UserID     uuid.UUID
}

// How many visible entries outrank this position. Rank = that + 1, which is what
// makes the rank on a cursor page exact instead of a guess carried in the token.
func (q *Queries) CountLeaderboardAbove(ctx context.Context, arg CountLeaderboardAboveParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLeaderboardAbove,
		arg.BucketKey,
		arg.Score,
		arg.AchievedAt,
		arg.UserID,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countLeaderboardEntries = `-- name: CountLeaderboardEntries :one
SELECT count(*) FROM leaderboard_entries
`

func (q *Queries) CountLeaderboardEntries(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countLeaderboardEntries)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const enumerateLeaderboardCells = `-- name: EnumerateLeaderboardCells :many
SELECT DISTINCT e.user_id, e.mode, e.duration_ms, e.word_count, e.lang,
                e.text_source_kind, e.quote_id
FROM leaderboard_eligible_runs e
WHERE (NOT $1::boolean
       OR EXISTS (SELECT 1 FROM auth_identities ai
                  WHERE ai.user_id = e.user_id AND ai.email_verified))
ORDER BY e.user_id, e.mode, e.duration_ms, e.word_count, e.lang,
         e.text_source_kind, e.quote_id
`

type EnumerateLeaderboardCellsRow struct {
	UserID         uuid.UUID
	Mode           string
	DurationMs     *int32
	WordCount      *int32
	Lang           string
	TextSourceKind string
	QuoteID        *uuid.UUID
}

// Every (player, bucket) cell that currently has an eligible run. The rebuild
// walks this and calls RecomputeLeaderboardCell on each, so the rebuilt table is
// produced by the same statement that maintains it incrementally.
//
// These are candidate COORDINATES, not board identities: two rows can name the
// same quote board (the language coordinates ride along and a quote board
// ignores them). Collapsing coordinates into the board they name is Bucket.Key's
// job and happens in Go, where the key has its one producer — Rebuild walks
// each DISTINCT bucket once.
func (q *Queries) EnumerateLeaderboardCells(ctx context.Context, requireVerifiedEmail bool) ([]EnumerateLeaderboardCellsRow, error) {
	rows, err := q.db.Query(ctx, enumerateLeaderboardCells, requireVerifiedEmail)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EnumerateLeaderboardCellsRow{}
	for rows.Next() {
		var i EnumerateLeaderboardCellsRow
		if err := rows.Scan(
			&i.UserID,
			&i.Mode,
			&i.DurationMs,
			&i.WordCount,
			&i.Lang,
			&i.TextSourceKind,
			&i.QuoteID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLeaderboardEntry = `-- name: GetLeaderboardEntry :one
SELECT user_id, display_name, run_id, score, wpm, raw, acc, grade, mods,
       achieved_at, quote_source
FROM leaderboard_rows
WHERE bucket_key = $1 AND user_id = $2
`

type GetLeaderboardEntryParams struct {
	BucketKey string
	UserID    uuid.UUID
}

type GetLeaderboardEntryRow struct {
	UserID      uuid.UUID
	DisplayName string
	RunID       uuid.UUID
	Score       int64
	Wpm         float64
	Raw         float64
	Acc         float64
	Grade       string
	Mods        json.RawMessage
	AchievedAt  time.Time
	QuoteSource *string
}

// One player's entry in one bucket. A banned player has none (the view), which
// is exactly the 204 the /me endpoint wants.
func (q *Queries) GetLeaderboardEntry(ctx context.Context, arg GetLeaderboardEntryParams) (GetLeaderboardEntryRow, error) {
	row := q.db.QueryRow(ctx, getLeaderboardEntry, arg.BucketKey, arg.UserID)
	var i GetLeaderboardEntryRow
	err := row.Scan(
		&i.UserID,
		&i.DisplayName,
		&i.RunID,
		&i.Score,
		&i.Wpm,
		&i.Raw,
		&i.Acc,
		&i.Grade,
		&i.Mods,
		&i.AchievedAt,
		&i.QuoteSource,
	)
	return i, err
}

const listLeaderboardBuckets = `-- name: ListLeaderboardBuckets :many
SELECT bucket_key, count(*)::bigint AS entries
FROM leaderboard_rows
GROUP BY bucket_key
ORDER BY bucket_key
`

type ListLeaderboardBucketsRow struct {
	BucketKey string
	Entries   int64
}

// The board index. Counts are ban-filtered like every other read, so a bucket
// whose only player is banned reports zero rather than one.
//
// Quote boards are in here alongside the language ones, and they are the reason
// this result is no longer bounded by the schema — see docs/LEADERBOARDS.md.
func (q *Queries) ListLeaderboardBuckets(ctx context.Context) ([]ListLeaderboardBucketsRow, error) {
	rows, err := q.db.Query(ctx, listLeaderboardBuckets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLeaderboardBucketsRow{}
	for rows.Next() {
		var i ListLeaderboardBucketsRow
		if err := rows.Scan(&i.BucketKey, &i.Entries); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeaderboardPageAfter = `-- name: ListLeaderboardPageAfter :many
SELECT user_id, display_name, run_id, score, wpm, raw, acc, grade, mods,
       achieved_at, quote_source
FROM leaderboard_rows
WHERE bucket_key = $1
  AND (score < $2
       OR (score = $2 AND achieved_at > $3)
       OR (score = $2 AND achieved_at = $3 AND user_id > $4))
ORDER BY score DESC, achieved_at ASC, user_id ASC
LIMIT $5
`

type ListLeaderboardPageAfterParams struct {
	BucketKey  string
	Score      int64
	AchievedAt time.Time
	UserID     uuid.UUID
	RowLimit   int32
}

type ListLeaderboardPageAfterRow struct {
	UserID      uuid.UUID
	DisplayName string
	RunID       uuid.UUID
	Score       int64
	Wpm         float64
	Raw         float64
	Acc         float64
	Grade       string
	Mods        json.RawMessage
	AchievedAt  time.Time
	QuoteSource *string
}

// The keyset continuation of the ordering above. Spelled out rather than as a
// row comparison because the directions are mixed (score DESC, the rest ASC).
func (q *Queries) ListLeaderboardPageAfter(ctx context.Context, arg ListLeaderboardPageAfterParams) ([]ListLeaderboardPageAfterRow, error) {
	rows, err := q.db.Query(ctx, listLeaderboardPageAfter,
		arg.BucketKey,
		arg.Score,
		arg.AchievedAt,
		arg.UserID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLeaderboardPageAfterRow{}
	for rows.Next() {
		var i ListLeaderboardPageAfterRow
		if err := rows.Scan(
			&i.UserID,
			&i.DisplayName,
			&i.RunID,
			&i.Score,
			&i.Wpm,
			&i.Raw,
			&i.Acc,
			&i.Grade,
			&i.Mods,
			&i.AchievedAt,
			&i.QuoteSource,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeaderboardPageFirst = `-- name: ListLeaderboardPageFirst :many
SELECT user_id, display_name, run_id, score, wpm, raw, acc, grade, mods,
       achieved_at, quote_source
FROM leaderboard_rows
WHERE bucket_key = $1
ORDER BY score DESC, achieved_at ASC, user_id ASC
LIMIT $2
`

type ListLeaderboardPageFirstParams struct {
	BucketKey string
	RowLimit  int32
}

type ListLeaderboardPageFirstRow struct {
	UserID      uuid.UUID
	DisplayName string
	RunID       uuid.UUID
	Score       int64
	Wpm         float64
	Raw         float64
	Acc         float64
	Grade       string
	Mods        json.RawMessage
	AchievedAt  time.Time
	QuoteSource *string
}

// Page one: best score first, earliest achievement first on a tie, user_id as
// the final tiebreak so the order is total (and therefore pageable).
func (q *Queries) ListLeaderboardPageFirst(ctx context.Context, arg ListLeaderboardPageFirstParams) ([]ListLeaderboardPageFirstRow, error) {
	rows, err := q.db.Query(ctx, listLeaderboardPageFirst, arg.BucketKey, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLeaderboardPageFirstRow{}
	for rows.Next() {
		var i ListLeaderboardPageFirstRow
		if err := rows.Scan(
			&i.UserID,
			&i.DisplayName,
			&i.RunID,
			&i.Score,
			&i.Wpm,
			&i.Raw,
			&i.Acc,
			&i.Grade,
			&i.Mods,
			&i.AchievedAt,
			&i.QuoteSource,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recomputeLeaderboardCell = `-- name: RecomputeLeaderboardCell :exec
WITH best AS (
    SELECT e.run_id, e.user_id, e.mode, e.duration_ms, e.word_count, e.lang, e.text_source_kind, e.quote_id, e.score, e.wpm, e.raw, e.acc, e.mods, e.achieved_at
    FROM leaderboard_eligible_runs e
    WHERE e.user_id = $2
      AND e.quote_id IS NOT DISTINCT FROM $3::uuid
      AND (e.quote_id IS NOT NULL
           OR (e.mode = $4
               AND e.duration_ms IS NOT DISTINCT FROM $5::int
               AND e.word_count IS NOT DISTINCT FROM $6::int
               AND e.lang = $7
               AND e.text_source_kind = $8))
      -- The economic barrier against throwaway accounts. Off by config, and
      -- flipping it needs a rebuild to take effect on existing runs.
      --
      -- Note ` + "`" + `ai.user_id = @user_id` + "`" + `, NOT ` + "`" + `= e.user_id` + "`" + `. The two are the same
      -- value — ` + "`" + `e.user_id = @user_id` + "`" + ` is asserted five lines above — but
      -- correlating on the column makes this a SubPlan the executor runs once
      -- per CANDIDATE RUN instead of an InitPlan it runs once per statement.
      -- Measured (docs/PERFORMANCE.md, zone 4): a six-run cell 34.6 ms → 8.0 ms,
      -- and a player with 100 000 runs in one bucket 1 m 30 s → 458 ms, which is
      -- the gate costing nothing at all. This projection runs inside the replay
      -- worker's verdict transaction, holding its row locks, so the difference
      -- is not academic.
      AND (NOT $9::boolean
           OR EXISTS (SELECT 1 FROM auth_identities ai
                      WHERE ai.user_id = $2 AND ai.email_verified))
    ORDER BY e.score DESC, e.achieved_at ASC, e.run_id ASC
    LIMIT 1
),
cleared AS (
    DELETE FROM leaderboard_entries le
    WHERE le.bucket_key = $1
      AND le.user_id = $2
      AND NOT EXISTS (SELECT 1 FROM best)
)
INSERT INTO leaderboard_entries
    (bucket_key, user_id, run_id, score, wpm, raw, acc, grade, mods, achieved_at,
     quote_source)
SELECT $1, b.user_id, b.run_id, b.score, b.wpm, b.raw, b.acc,
       run_grade(b.acc), b.mods, b.achieved_at, q.source
FROM best b
         LEFT JOIN quotes q ON q.id = b.quote_id
ON CONFLICT (bucket_key, user_id) DO UPDATE
    SET run_id      = EXCLUDED.run_id,
        score       = EXCLUDED.score,
        wpm         = EXCLUDED.wpm,
        raw         = EXCLUDED.raw,
        acc         = EXCLUDED.acc,
        grade       = EXCLUDED.grade,
        mods        = EXCLUDED.mods,
        achieved_at = EXCLUDED.achieved_at,
        quote_source = EXCLUDED.quote_source
    -- An unchanged best is left physically alone.
    WHERE leaderboard_entries.run_id <> EXCLUDED.run_id
`

type RecomputeLeaderboardCellParams struct {
	BucketKey            string
	UserID               uuid.UUID
	QuoteID              *uuid.UUID
	Mode                 string
	DurationMs           *int32
	WordCount            *int32
	Lang                 string
	TextSourceKind       string
	RequireVerifiedEmail bool
}

// Set one (bucket, player) cell to that player's best eligible run, or clear it
// when nothing is left. This single statement covers every case:
//
//	new personal best      the ORDER BY picks the new run
//	worse run submitted    the ORDER BY keeps the old one, DO UPDATE no-ops
//	run demoted            it drops out of leaderboard_eligible_runs and the
//	                       next best takes the slot
//	only entry demoted     `best` is empty, so the DELETE fires
//
// Writing it as "recompute the cell" rather than "upsert if better" is what
// makes demotion correct for free, and it is why a rebuild can reuse this
// statement verbatim instead of reimplementing the rule.
//
// Siblings are matched on the bucket COMPONENTS, never by parsing bucket_key:
// the key's format has exactly one producer, and it is in Go.
//
// quote_id is the first component and it decides which of the others count. A
// quote board has no mode, no size, no language and no text-source dimension —
// the quote IS the dimension (SCORING_CONCEPT §6) — so for a quote cell the
// language coordinates are not merely equal-to-something, they are NOT ASKED.
// That is what makes the two exclusions structural rather than remembered:
//
//	language cell  quote_id IS NULL      → a quote run cannot be a sibling
//	quote cell     quote_id = <that one> → a seeded run cannot be a sibling
//
// and both hold for the projection AND the rebuild, because this is the only
// statement either of them writes through.
//
// The quote's attribution is resolved ONCE, by the LEFT JOIN below, for the
// single row that won the cell: not per candidate run, and never per read. On a
// language board b.quote_id is NULL, the index probe matches nothing and the
// column stays NULL, which is why no language board pays for the feature. LEFT
// rather than inner because of THAT case, not because the quote might be
// missing: a language cell has no quote id at all, and an inner join would drop
// every language board's row. On a quote cell the row is guaranteed — the
// eligible view resolves quote_id through `quotes`, so a candidate exists only
// if its quote does, which is what makes `source` non-optional on a quote board
// rather than merely usually present.
func (q *Queries) RecomputeLeaderboardCell(ctx context.Context, arg RecomputeLeaderboardCellParams) error {
	_, err := q.db.Exec(ctx, recomputeLeaderboardCell,
		arg.BucketKey,
		arg.UserID,
		arg.QuoteID,
		arg.Mode,
		arg.DurationMs,
		arg.WordCount,
		arg.Lang,
		arg.TextSourceKind,
		arg.RequireVerifiedEmail,
	)
	return err
}

const runBucketCell = `-- name: RunBucketCell :one

SELECT r.user_id, r.mode, r.duration_ms, r.word_count, r.lang,
       run_text_source_kind(r.setup)::text AS text_source_kind,
       q.id AS quote_id
FROM runs r
         LEFT JOIN quotes q ON q.id = run_quote_id(r.setup)
WHERE r.id = $1
`

type RunBucketCellRow struct {
	UserID         uuid.UUID
	Mode           string
	DurationMs     *int32
	WordCount      *int32
	Lang           string
	TextSourceKind string
	QuoteID        *uuid.UUID
}

// Bucketed score leaderboards (docs/LEADERBOARDS.md).
//
// Reads go through leaderboard_rows (ban-filtered by construction); writes go
// through RecomputeLeaderboardCell, which is the ONLY statement that mutates
// the table — promotion, demotion and rebuild are all the same operation.
// The cell a run belongs to, resolved WITHOUT looking at its status: a run that
// just lost its accepted status still has to say which cell to recompute.
//
// These are the same coordinates leaderboard_eligible_runs carries, read
// straight off the run: which of them name the cell is Bucket's decision (a
// quote board has only its quote), and the projection and the rebuild agree
// because they build the bucket through the same constructor.
//
// The quote id is resolved through `quotes` rather than lifted out of the setup
// document, so an id that names nothing yields NULL here exactly as it does in
// the eligible view — one row, one primary-key probe, on a query that already
// runs once per verdict.
func (q *Queries) RunBucketCell(ctx context.Context, runID uuid.UUID) (RunBucketCellRow, error) {
	row := q.db.QueryRow(ctx, runBucketCell, runID)
	var i RunBucketCellRow
	err := row.Scan(
		&i.UserID,
		&i.Mode,
		&i.DurationMs,
		&i.WordCount,
		&i.Lang,
		&i.TextSourceKind,
		&i.QuoteID,
	)
	return i, err
}
